#!/usr/bin/env bash
set -euo pipefail

# Audit A6 — exactly one ajv-over-the-spec validator, and it is generated.
#
# There used to be one hand-configured Ajv setup, in `apps/gateway`, which
# only the backend could reach. make-meaning needed the same validation for
# its consumer teeth, and writing a second setup would have hand-restated the
# first's semantics — the OpenAPI-3.0 `nullable`→draft-07 conversion, the
# `example`/`discriminator` keyword allowlist, `coerceTypes`, `addFormats`.
# A drift in any one of them yields a FALSE GREEN: a validation that passes
# because the two setups disagree, not because the payload is right.
#
# A6 — no package configures Ajv against the OpenAPI spec. The validators are
#      generated from `specs/openapi.json` into `@semiont/core/openapi` by
#      scripts/spec/generate-validators.mjs, which is the only place that may
#      construct an Ajv instance over spec schemas.
#
# See .plans/GRAPH-ANNOTATION-CODEC.md (P4, D8 = generate).

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GENERATOR="scripts/spec/generate-validators.mjs"

violations=0

# Ajv setups that are NOT over the OpenAPI spec, each with its reason. A6 is
# about ONE authority — the spec — not about banning Ajv; the config schema is
# a different authority with a different lifecycle. Entries need a reason, so
# an addition is a decision rather than a reflex.
ALLOWED_REASON_config_schema_test="validates TOML config against config.schema.json — a different authority from specs/openapi.json"
ALLOWED_PATHS=(
  "packages/core/src/__tests__/config/config-schema.test.ts"
)

is_allowed() {
  local file="$1"
  for allowed in "${ALLOWED_PATHS[@]}"; do
    [[ "$file" == *"$allowed" ]] && return 0
  done
  return 1
}

echo "🔍 Auditing the spec validator (A6)..."

# ---------------------------------------------------------------------------
# A6a: only the generator constructs Ajv.
# ---------------------------------------------------------------------------
offenders=""
while IFS= read -r hit; do
  [ -z "$hit" ] && continue
  file="${hit%%:*}"
  is_allowed "$file" && continue
  offenders+="$hit"$'\n'
done < <(grep -rn "new Ajv(" \
      --include="*.ts" --include="*.tsx" --include="*.mjs" --include="*.js" \
      "$REPO_ROOT/packages" "$REPO_ROOT/apps" "$REPO_ROOT/scripts" 2>/dev/null \
      | grep -v "/node_modules/" \
      | grep -v "/dist/" \
      | grep -v "$GENERATOR" || true)

if [ -n "$offenders" ]; then
  echo ""
  echo "❌ A6: an Ajv instance is constructed outside the generator."
  echo "   Spec validation comes from \`@semiont/core/openapi\`, generated by"
  echo "   $GENERATOR. A second setup restates its semantics and drifts."
  printf '%s' "$offenders" | sed 's|^|   |'
  violations=$((violations + 1))
fi

# ---------------------------------------------------------------------------
# A6b: nobody re-implements the 3.0 → draft-07 conversion.
#
# `nullable` is OpenAPI vocabulary Ajv does not know. Converting it is the
# generator's job; a copy elsewhere is the mirror this gate exists to stop.
# ---------------------------------------------------------------------------
if converters=$(grep -rn "nullable === true\|convertNullable" \
      --include="*.ts" --include="*.tsx" --include="*.mjs" --include="*.js" \
      "$REPO_ROOT/packages" "$REPO_ROOT/apps" "$REPO_ROOT/scripts" 2>/dev/null \
      | grep -v "/node_modules/" \
      | grep -v "/dist/" \
      | grep -v "$GENERATOR"); then
  echo ""
  echo "❌ A6: the OpenAPI 3.0 \`nullable\` conversion is reimplemented."
  echo "   It belongs to $GENERATOR and runs at build time."
  echo "$converters" | sed 's|^|   |'
  violations=$((violations + 1))
fi

if [ "$violations" -eq 0 ]; then
  echo "✅ A6: one generated spec validator, no second Ajv setup."
else
  echo ""
  echo "$violations A6 violation(s)."
  exit 1
fi
