// ⚠ GENERATED FILE — do not edit.
//
// Authority:   specs/src/bus/registry.json  (channels, payloads, operations)
// Regenerate:  node scripts/bus/generate-ts.mjs
// Go counterpart: node scripts/bus/generate-go.mjs → packages/sdk-go/bus
//
// Payload schemas themselves live in the OpenAPI components; the registry
// names which one each channel carries. Add or change a channel THERE.

import type { EventName } from './bus-protocol';

/** Where a channel sits relative to the hub: emitted toward it, delivered
 *  from it (the fan-in set — BRIDGED_CHANNELS, by construction), or never on
 *  the wire at all. */
export type ChannelDirection = 'outbound' | 'inbound' | 'in-process';

/** How an INBOUND channel is delivered. Correlated replies are
 *  owner-addressed; streaming (progress) frames refresh a claim's TTL but are
 *  never retained; broadcasts go to every subscriber in scope. Only inbound
 *  channels carry this — absence on the others is a decision, not a gap. */
export type ChannelDelivery = 'correlated' | 'streaming' | 'broadcast';

export interface ChannelAttrs {
  /** In PERSISTED_EVENT_TYPES — lands in the event log, the system of record. */
  readonly recorded: boolean;
  readonly direction: ChannelDirection;
  readonly delivery?: ChannelDelivery;
}

export const CHANNEL_ATTRS = {
  'yield:created':                    { recorded: true, direction: 'inbound', delivery: 'broadcast' },
  'yield:cloned':                     { recorded: true, direction: 'inbound', delivery: 'broadcast' },
  'yield:updated':                    { recorded: true, direction: 'inbound', delivery: 'broadcast' },
  'yield:moved':                      { recorded: true, direction: 'inbound', delivery: 'broadcast' },
  'yield:representation-added':       { recorded: true, direction: 'in-process' },
  'yield:representation-removed':     { recorded: true, direction: 'in-process' },
  'yield:create':                     { recorded: false, direction: 'outbound' },
  'yield:clone-persist':              { recorded: false, direction: 'outbound' },
  'yield:update':                     { recorded: false, direction: 'outbound' },
  'yield:mv':                         { recorded: false, direction: 'in-process' },
  'yield:clone':                      { recorded: false, direction: 'in-process' },
  'yield:clone-token-requested':      { recorded: false, direction: 'outbound' },
  'yield:clone-resource-requested':   { recorded: false, direction: 'outbound' },
  'yield:clone-create':               { recorded: false, direction: 'outbound' },
  'yield:create-ok':                  { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'yield:create-failed':              { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'yield:clone-persist-ok':           { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'yield:clone-persist-failed':       { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'yield:update-ok':                  { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'yield:update-failed':              { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'yield:move-failed':                { recorded: false, direction: 'in-process' },
  'yield:clone-token-generated':      { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'yield:clone-token-failed':         { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'yield:clone-resource-result':      { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'yield:clone-resource-failed':      { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'yield:clone-created':              { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'yield:clone-create-failed':        { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'mark:added':                       { recorded: true, direction: 'in-process' },
  'mark:removed':                     { recorded: true, direction: 'in-process' },
  'mark:body-updated':                { recorded: true, direction: 'in-process' },
  'mark:entity-tag-added':            { recorded: true, direction: 'in-process' },
  'mark:entity-tag-removed':          { recorded: true, direction: 'in-process' },
  'mark:archived':                    { recorded: true, direction: 'in-process' },
  'mark:unarchived':                  { recorded: true, direction: 'in-process' },
  'mark:create-request':              { recorded: false, direction: 'outbound' },
  'mark:create':                      { recorded: false, direction: 'in-process' },
  'mark:delete':                      { recorded: false, direction: 'outbound' },
  'mark:update-body':                 { recorded: false, direction: 'in-process' },
  'mark:archive':                     { recorded: false, direction: 'outbound' },
  'mark:unarchive':                   { recorded: false, direction: 'outbound' },
  'mark:update-entity-types':         { recorded: false, direction: 'outbound' },
  'mark:create-ok':                   { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'mark:create-failed':               { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'mark:commit':                      { recorded: false, direction: 'outbound' },
  'mark:commit-ok':                   { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'mark:commit-failed':               { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'mark:delete-ok':                   { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'mark:delete-failed':               { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'mark:archive-ok':                  { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'mark:archive-failed':              { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'mark:unarchive-ok':                { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'mark:unarchive-failed':            { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'mark:update-entity-types-ok':      { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'mark:update-entity-types-failed':  { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'mark:body-update-failed':          { recorded: false, direction: 'in-process' },
  'mark:select-comment':              { recorded: false, direction: 'in-process' },
  'mark:select-tag':                  { recorded: false, direction: 'in-process' },
  'mark:select-assessment':           { recorded: false, direction: 'in-process' },
  'mark:select-reference':            { recorded: false, direction: 'in-process' },
  'mark:requested':                   { recorded: false, direction: 'in-process' },
  'mark:cancel-pending':              { recorded: false, direction: 'in-process' },
  'mark:submit':                      { recorded: false, direction: 'in-process' },
  'mark:assist-request':              { recorded: false, direction: 'in-process' },
  'mark:progress-dismiss':            { recorded: false, direction: 'in-process' },
  'mark:assist-timeout':              { recorded: false, direction: 'in-process' },
  'mark:create-error':                { recorded: false, direction: 'in-process' },
  'mark:delete-error':                { recorded: false, direction: 'in-process' },
  'bind:body-error':                  { recorded: false, direction: 'in-process' },
  'frame:entity-type-added':          { recorded: true, direction: 'inbound', delivery: 'broadcast' },
  'frame:tag-schema-added':           { recorded: true, direction: 'inbound', delivery: 'broadcast' },
  'frame:add-entity-type':            { recorded: false, direction: 'outbound' },
  'frame:add-tag-schema':             { recorded: false, direction: 'outbound' },
  'frame:entity-type-add-ok':         { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'frame:entity-type-add-failed':     { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'frame:tag-schema-add-ok':          { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'frame:tag-schema-add-failed':      { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'bind:initiate':                    { recorded: false, direction: 'in-process' },
  'bind:update-body':                 { recorded: false, direction: 'outbound' },
  'bind:body-updated':                { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'bind:body-update-failed':          { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'match:search-requested':           { recorded: false, direction: 'outbound' },
  'match:search-results':             { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'match:search-failed':              { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'gather:requested':                 { recorded: false, direction: 'outbound' },
  'gather:complete':                  { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'gather:failed':                    { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'gather:resource-requested':        { recorded: false, direction: 'outbound' },
  'gather:resource-complete':         { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'gather:resource-failed':           { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'gather:summary-requested':         { recorded: false, direction: 'outbound' },
  'gather:summary-result':            { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'gather:summary-failed':            { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'gather:annotation-progress':       { recorded: false, direction: 'inbound', delivery: 'streaming' },
  'browse:resource-requested':        { recorded: false, direction: 'outbound' },
  'browse:resource-result':           { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:resource-failed':           { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:anchored-text-requested':   { recorded: false, direction: 'outbound' },
  'browse:anchored-text-result':      { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:anchored-text-failed':      { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:resources-requested':       { recorded: false, direction: 'outbound' },
  'browse:resources-result':          { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:resources-failed':          { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:annotations-requested':     { recorded: false, direction: 'outbound' },
  'browse:annotations-result':        { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:annotations-failed':        { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:annotation-requested':      { recorded: false, direction: 'outbound' },
  'browse:annotation-result':         { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:annotation-failed':         { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:events-requested':          { recorded: false, direction: 'outbound' },
  'browse:events-result':             { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:events-failed':             { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:annotation-history-requested': { recorded: false, direction: 'outbound' },
  'browse:annotation-history-result': { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:annotation-history-failed': { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:annotation-context-requested': { recorded: false, direction: 'outbound' },
  'browse:annotation-context-result': { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:annotation-context-failed': { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:referenced-by-requested':   { recorded: false, direction: 'outbound' },
  'browse:referenced-by-result':      { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:referenced-by-failed':      { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:entity-types-requested':    { recorded: false, direction: 'outbound' },
  'browse:entity-types-result':       { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:entity-types-failed':       { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:tag-schemas-requested':     { recorded: false, direction: 'outbound' },
  'browse:tag-schemas-result':        { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:tag-schemas-failed':        { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:agents-requested':          { recorded: false, direction: 'outbound' },
  'browse:agents-result':             { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:agents-failed':             { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:directory-requested':       { recorded: false, direction: 'outbound' },
  'browse:directory-result':          { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:directory-failed':          { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'browse:click':                     { recorded: false, direction: 'inbound', delivery: 'broadcast' },
  'browse:resource-open':             { recorded: false, direction: 'inbound', delivery: 'broadcast' },
  'browse:resource-viewed':           { recorded: false, direction: 'inbound', delivery: 'broadcast' },
  'browse:entity-type-clicked':       { recorded: false, direction: 'in-process' },
  'panel:toggle':                     { recorded: false, direction: 'in-process' },
  'panel:open':                       { recorded: false, direction: 'in-process' },
  'panel:close':                      { recorded: false, direction: 'in-process' },
  'shell:sidebar-toggle':             { recorded: false, direction: 'in-process' },
  'tabs:close':                       { recorded: false, direction: 'in-process' },
  'tabs:reorder':                     { recorded: false, direction: 'in-process' },
  'nav:link-clicked':                 { recorded: false, direction: 'in-process' },
  'nav:push':                         { recorded: false, direction: 'in-process' },
  'nav:external':                     { recorded: false, direction: 'in-process' },
  'beckon:hover':                     { recorded: false, direction: 'in-process' },
  'beckon:focus':                     { recorded: false, direction: 'inbound', delivery: 'broadcast' },
  'beckon:sparkle':                   { recorded: false, direction: 'inbound', delivery: 'broadcast' },
  'job:started':                      { recorded: true, direction: 'in-process' },
  'job:completed':                    { recorded: true, direction: 'in-process' },
  'job:failed':                       { recorded: true, direction: 'in-process' },
  'job:start':                        { recorded: false, direction: 'in-process' },
  'job:report-progress':              { recorded: false, direction: 'inbound', delivery: 'broadcast' },
  'job:complete':                     { recorded: false, direction: 'inbound', delivery: 'broadcast' },
  'job:fail':                         { recorded: false, direction: 'inbound', delivery: 'broadcast' },
  'job:checkpoint':                   { recorded: false, direction: 'outbound' },
  'job:queued':                       { recorded: false, direction: 'inbound', delivery: 'broadcast' },
  'job:cancel-requested':             { recorded: false, direction: 'outbound' },
  'job:cancel':                       { recorded: false, direction: 'outbound' },
  'job:status-requested':             { recorded: false, direction: 'outbound' },
  'job:create':                       { recorded: false, direction: 'outbound' },
  'job:claim':                        { recorded: false, direction: 'outbound' },
  'job:status-result':                { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'job:status-failed':                { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'job:created':                      { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'job:create-failed':                { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'job:claimed':                      { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'job:claim-failed':                 { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'job:cancel-ok':                    { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'job:cancel-failed':                { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'weave:applied':                    { recorded: false, direction: 'in-process' },
  'smelt:settled':                    { recorded: false, direction: 'inbound', delivery: 'broadcast' },
  'weave:rebuild':                    { recorded: false, direction: 'outbound' },
  'weave:rebuild-ok':                 { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'weave:rebuild-failed':             { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'smelt:rebuild-anchors':            { recorded: false, direction: 'outbound' },
  'smelt:rebuild-anchors-ok':         { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'smelt:rebuild-anchors-failed':     { recorded: false, direction: 'inbound', delivery: 'correlated' },
  'settings:theme-changed':           { recorded: false, direction: 'in-process' },
  'settings:line-numbers-toggled':    { recorded: false, direction: 'in-process' },
  'settings:locale-changed':          { recorded: false, direction: 'in-process' },
  'settings:hover-delay-changed':     { recorded: false, direction: 'in-process' },
  'stream-connected':                 { recorded: false, direction: 'in-process' },
  'replay-window-exceeded':           { recorded: false, direction: 'in-process' },
  'bus:resume-gap':                   { recorded: false, direction: 'inbound', delivery: 'broadcast' },
  'session:joined':                   { recorded: false, direction: 'inbound', delivery: 'broadcast' },
  'session:left':                     { recorded: false, direction: 'inbound', delivery: 'broadcast' },
} as const satisfies Record<EventName, ChannelAttrs>;

const BY_CHANNEL: ReadonlyMap<string, ChannelAttrs> = new Map(Object.entries(CHANNEL_ATTRS));

/** String-keyed accessor for boundary code that has not yet narrowed to
 *  EventName. Undefined means "not a channel", never "unclassified" — the
 *  satisfies above makes unclassified unrepresentable. */
export const channelAttrsOf = (channel: string): ChannelAttrs | undefined => BY_CHANNEL.get(channel);
