name: 🔒 Security Vulnerability Report
description: Report a security vulnerability (please use private reporting for sensitive issues)
title: "[SECURITY] "
labels: ["security", "priority-high"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Report
        
        **For sensitive security issues, please use [GitHub's private vulnerability reporting](https://github.com/The-AI-Alliance/semiont/security/advisories/new) instead of this public issue.**
        
        This form is for non-sensitive security improvements or issues that are already public.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Low (Information disclosure, minor security hardening)
        - Medium (Authentication bypass, privilege escalation)
        - High (Admin access compromise, data exposure)
        - Critical (Full system compromise, credential theft)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the system is affected?
      options:
        - Frontend (React/Next.js application)
        - Backend (Node.js API)
        - Authentication (OAuth/JWT)
        - Admin Routes (Admin panel access)
        - Database (Prisma/PostgreSQL)
        - Infrastructure (AWS/CDK)
        - CI/CD (GitHub Actions)
        - Dependencies (npm packages)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability in detail
      placeholder: |
        - What is the vulnerability?
        - How can it be exploited?
        - What is the potential impact?
        - Are there any prerequisites for exploitation?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the vulnerability
      placeholder: |
        1. Go to...
        2. Click on...
        3. Enter...
        4. Observe that...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Security Impact
      description: What could an attacker achieve by exploiting this vulnerability?
      placeholder: |
        - Data that could be accessed
        - Systems that could be compromised
        - Users that could be affected
        - Business impact
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence/Proof of Concept
      description: |
        Provide evidence of the vulnerability (screenshots, logs, etc.)
        **Do not include actual credentials, tokens, or sensitive data**
      placeholder: |
        - Screenshots showing the issue
        - Log entries (sanitized)
        - Network requests/responses (sanitized)
        - Code snippets demonstrating the issue

  - type: textarea
    id: suggested_fix
    attributes:
      label: Suggested Fix
      description: If you have ideas for how to fix this vulnerability, please share them
      placeholder: |
        - Proposed solution approach
        - Code changes needed
        - Configuration updates required
        - Additional security measures

  - type: checkboxes
    id: security_tests
    attributes:
      label: Security Test Status
      description: Have you run our security tests to verify this issue?
      options:
        - label: I have run `npm run test:security` in the frontend
        - label: I have run `npm run test:security` in the backend
        - label: The security tests detect this vulnerability
        - label: The security tests pass despite this vulnerability
        - label: I have not run the security tests

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details where the vulnerability was discovered
      placeholder: |
        - Browser (if frontend): Chrome 120, Firefox 119, etc.
        - Node.js version: 
        - Operating System: 
        - Deployment environment: Development, Staging, Production

  - type: checkboxes
    id: checklist
    attributes:
      label: Security Checklist
      description: Please confirm the following
      options:
        - label: This vulnerability could impact user security or data privacy
          required: true
        - label: I have not disclosed this vulnerability publicly before reporting it here
          required: true
        - label: I understand that sensitive security issues should use private reporting
          required: true
        - label: I have sanitized any sensitive information from this report
          required: true

  - type: markdown
    attributes:
      value: |
        ## 🔒 Security Response Process
        
        1. **Triage**: Security issues are triaged within 24 hours
        2. **Assessment**: Severity and impact assessment completed within 48 hours  
        3. **Fix Development**: Security fixes prioritized based on severity
        4. **Testing**: All security fixes must pass security tests
        5. **Deployment**: Critical and high severity issues get emergency deployment
        6. **Disclosure**: Public disclosure only after fix is deployed
        
        **Thank you for helping keep Semiont secure!** 🛡️