/**
 * KnowledgeBase — a connection to a Semiont backend instance.
 *
 * Each KB has its own JWT, its own API base URL, and its own session.
 * The user is "authenticated against KB X" — never globally authenticated.
 */
export interface KnowledgeBase {
  id: string;
  label: string;
  host: string;
  port: number;
  protocol: 'http' | 'https';
  email: string;
  gitBranch?: string;
}

/**
 * Input shape for adding a new KB. The id is generated by the provider.
 */
export type NewKnowledgeBase = Omit<KnowledgeBase, 'id'>;

/**
 * Status of the locally-stored credential for a KB. Derived from the
 * presence and validity of the JWT in localStorage.
 */
export type KbSessionStatus = 'authenticated' | 'expired' | 'signed-out' | 'unreachable';
