// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package launcher

import "encoding/json"
import "fmt"
import "reflect"

// One knowledge base the Semiont launcher manages on this machine, as published in
// the discovery document (see DiscoveryDocument). Endpoints and identity only —
// never credentials; login remains the consumer's per-KB business.
type DiscoveredKB struct {
	// The KB's did:web identifier as recorded from its committed .semiont/config —
	// the permanent identity stamped into its event log. Prefer this as a merge key:
	// ports are reallocated across restarts; the did follows the KB.
	Did *string `json:"did,omitempty,omitzero"`

	// Hostname the KB is reachable on from this machine (today always "localhost" —
	// local stacks bind locally and codespace KBs arrive through a local port
	// forward)
	Host string `json:"host"`

	// The agent that owns this entry's lifecycle (the launcher writes
	// "semiont-launcher"). Consumers treat managed entries as authoritative for
	// themselves — upsert on appearance, remove on disappearance — and never touch
	// entries they did not write.
	ManagedBy string `json:"managedBy"`

	// Where the stack actually runs. "local": containers on this machine.
	// "codespace": a GitHub-hosted VM whose KB is port-forwarded here.
	Placement DiscoveredKBPlacement `json:"placement"`

	// Local TCP port of the KB's API (the backend port for a local stack; the
	// allocated forward port for a codespace stack)
	Port int `json:"port"`

	// owner/name GitHub slug — present for codespace placements, where the repo is
	// the stack's identity
	Repo *string `json:"repo,omitempty,omitzero"`

	// Human-readable site name from the KB's .semiont/config, for display
	SiteName *string `json:"siteName,omitempty,omitzero"`
}

type DiscoveredKBPlacement string

const DiscoveredKBPlacementCodespace DiscoveredKBPlacement = "codespace"
const DiscoveredKBPlacementLocal DiscoveredKBPlacement = "local"

var enumValues_DiscoveredKBPlacement = []interface{}{
	"local",
	"codespace",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DiscoveredKBPlacement) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DiscoveredKBPlacement {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_DiscoveredKBPlacement, v)
	}
	*j = DiscoveredKBPlacement(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DiscoveredKB) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["host"]; raw != nil && !ok {
		return fmt.Errorf("field host in DiscoveredKB: required")
	}
	if _, ok := raw["managedBy"]; raw != nil && !ok {
		return fmt.Errorf("field managedBy in DiscoveredKB: required")
	}
	if _, ok := raw["placement"]; raw != nil && !ok {
		return fmt.Errorf("field placement in DiscoveredKB: required")
	}
	if _, ok := raw["port"]; raw != nil && !ok {
		return fmt.Errorf("field port in DiscoveredKB: required")
	}
	type Plain DiscoveredKB
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DiscoveredKB(plain)
	return nil
}

// The launcher's KB discovery document — the schema authority for
// <stateDir>/discovery/kbs.json, which the semiont launcher (Go, apps/launcher)
// regenerates on every stack mutation and the frontend container mounts read-only
// at /discovery. NOT an API endpoint: a static document fetched same-origin by
// browsers (via the frontend's static server) or read from disk by local Node
// consumers. An empty kbs list is meaningful ("the launcher manages nothing right
// now") and distinct from an absent file. Design record:
// .plans/BROWSER-KB-DISCOVERY.md.
type DiscoveryDocument struct {
	// Every KB the launcher currently manages, local and forwarded
	Kbs []DiscoveredKB `json:"kbs"`

	// Document schema version. Consumers MUST check it and ignore documents they do
	// not understand.
	Version DiscoveryDocumentVersion `json:"version"`
}

type DiscoveryDocumentVersion int

var enumValues_DiscoveryDocumentVersion = []interface{}{
	1,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DiscoveryDocumentVersion) UnmarshalJSON(value []byte) error {
	var v int
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DiscoveryDocumentVersion {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_DiscoveryDocumentVersion, v)
	}
	*j = DiscoveryDocumentVersion(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DiscoveryDocument) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["kbs"]; raw != nil && !ok {
		return fmt.Errorf("field kbs in DiscoveryDocument: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in DiscoveryDocument: required")
	}
	type Plain DiscoveryDocument
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DiscoveryDocument(plain)
	return nil
}
