# Generated from specs/src/bus/registry.json; do not edit.
# Regenerate: node scripts/bus/generate-python.mjs

"""Every channel of the bus, typed by the payload it carries.

A constant names its channel and holds its payload's type, so a function that
takes a `Channel[P]` and a `P` is refused another channel's payload by a type
checker. The payload types are the protocol's own (`semiont.types`); which
belongs to which channel is the registry's to say, and is derived here from
each channel's shape.

A channel a resource's scope carries is a `ScopedChannel[P]`, by the
registry's `audience`: it is read for a resource, and a type checker refuses
a read of one that names none.
"""

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final, Literal

from semiont.channel import AnyChannel, Channel, Empty, Response, ScopedChannel
from semiont.types import (
    BeckonFocusEvent,
    BeckonHoverEvent,
    BeckonSparkleEvent,
    BindBodyUpdated,
    BindInitiateCommand,
    BindUpdateBodyCommand,
    BrowseAgentsRequest,
    BrowseAgentsResult,
    BrowseAnchoredTextRequest,
    BrowseAnchoredTextResult,
    BrowseAnnotationHistoryRequest,
    BrowseAnnotationHistoryResult,
    BrowseAnnotationRequest,
    BrowseAnnotationResult,
    BrowseAnnotationsRequest,
    BrowseAnnotationsResult,
    BrowseClickEvent,
    BrowseDirectoryFailed,
    BrowseDirectoryRequest,
    BrowseDirectoryResult,
    BrowseEntityTypeClickedEvent,
    BrowseEntityTypesRequest,
    BrowseEntityTypesResult,
    BrowseEventsRequest,
    BrowseEventsResult,
    BrowseExternalNavigateEvent,
    BrowseKbRequest,
    BrowseKbResult,
    BrowseLinkClickedEvent,
    BrowsePanelOpenEvent,
    BrowsePanelToggleEvent,
    BrowseResourceCloseEvent,
    BrowseResourceOpenEvent,
    BrowseResourceReorderEvent,
    BrowseResourceRequest,
    BrowseResourceResult,
    BrowseResourceViewedEvent,
    BrowseResourcesRequest,
    BrowseResourcesResult,
    BrowseRouterPushEvent,
    BrowseTagSchemasRequest,
    BrowseTagSchemasResult,
    BusResumeGap,
    CloneResourceWithTokenResponse,
    CommandError,
    ContextualSummaryResponse,
    EnrichedResourceEvent,
    FrameAddEntityTypeCommand,
    FrameAddTagSchemaCommand,
    GatherAnnotationComplete,
    GatherAnnotationRequest,
    GatherFailed,
    GatherReferencedByRequest,
    GatherReferencedByResult,
    GatherResourceComplete,
    GatherResourceFailed,
    GatherResourceRequest,
    GatherSummaryRequest,
    GetResourceByTokenResponse,
    InferenceLimitsRequest,
    InferenceLimitsResult,
    JobAssignCommand,
    JobCancelCommand,
    JobCancelRequest,
    JobCancelResult,
    JobCheckpointCommand,
    JobClaimCommand,
    JobClaimedResult,
    JobCompleteCommand,
    JobCreateCommand,
    JobCreatedResult,
    JobFailCommand,
    JobQueuedEvent,
    JobReportProgressCommand,
    JobStartCommand,
    JobStatusRequest,
    JobStatusResult,
    MarkArchiveCommand,
    MarkCommitCommand,
    MarkCommitOk,
    MarkCreateCommand,
    MarkCreateOk,
    MarkCreateRequest,
    MarkDelegateRequestEvent,
    MarkDelegateTimeoutEvent,
    MarkDeleteCommand,
    MarkDeleteOk,
    MarkRequestedEvent,
    MarkSubmitEvent,
    MarkUnarchiveCommand,
    MarkUpdateBodyCommand,
    MarkUpdateEntityTypesCommand,
    MatchResourcesRequest,
    MatchResourcesResult,
    MatchSearchFailed,
    MatchSearchRequest,
    MatchSearchResult,
    PersonProfileCommand,
    ResourceErrorEvent,
    SelectionData,
    SessionJoinedEvent,
    SessionLeftEvent,
    SettingsHoverDelayChangedEvent,
    SettingsLocaleChangedEvent,
    SettingsThemeChangedEvent,
    SmeltRebuildAnchorsCommand,
    SmeltSettled,
    StoredEventResponse,
    WeaveApplied,
    WeaveRebuildCommand,
    YieldCloneCreateCommand,
    YieldCloneCreated,
    YieldClonePersistCommand,
    YieldClonePersistOk,
    YieldCloneResourceRequest,
    YieldCloneTokenRequest,
    YieldCreateCommand,
    YieldCreateOk,
    YieldMoveFailed,
    YieldMvCommand,
    YieldUpdateCommand,
    YieldUpdateOk,
)

__all__ = [
    "BRIDGED_CHANNELS",
    "CHANNELS",
    "CHANNEL_NAMES",
    "RESOURCE_SCOPED_CHANNELS",
    "BECKON_FOCUS",
    "BECKON_HOVER",
    "BECKON_SPARKLE",
    "BIND_BODY_ERROR",
    "BIND_BODY_UPDATED",
    "BIND_BODY_UPDATE_FAILED",
    "BIND_INITIATE",
    "BIND_UPDATE_BODY",
    "BROWSE_AGENTS_FAILED",
    "BROWSE_AGENTS_REQUESTED",
    "BROWSE_AGENTS_RESULT",
    "BROWSE_ANCHORED_TEXT_FAILED",
    "BROWSE_ANCHORED_TEXT_REQUESTED",
    "BROWSE_ANCHORED_TEXT_RESULT",
    "BROWSE_ANNOTATIONS_FAILED",
    "BROWSE_ANNOTATIONS_REQUESTED",
    "BROWSE_ANNOTATIONS_RESULT",
    "BROWSE_ANNOTATION_FAILED",
    "BROWSE_ANNOTATION_HISTORY_FAILED",
    "BROWSE_ANNOTATION_HISTORY_REQUESTED",
    "BROWSE_ANNOTATION_HISTORY_RESULT",
    "BROWSE_ANNOTATION_REQUESTED",
    "BROWSE_ANNOTATION_RESULT",
    "BROWSE_CLICK",
    "BROWSE_DIRECTORY_FAILED",
    "BROWSE_DIRECTORY_REQUESTED",
    "BROWSE_DIRECTORY_RESULT",
    "BROWSE_ENTITY_TYPES_FAILED",
    "BROWSE_ENTITY_TYPES_REQUESTED",
    "BROWSE_ENTITY_TYPES_RESULT",
    "BROWSE_ENTITY_TYPE_CLICKED",
    "BROWSE_EVENTS_FAILED",
    "BROWSE_EVENTS_REQUESTED",
    "BROWSE_EVENTS_RESULT",
    "BROWSE_KB_FAILED",
    "BROWSE_KB_REQUESTED",
    "BROWSE_KB_RESULT",
    "BROWSE_RESOURCES_FAILED",
    "BROWSE_RESOURCES_REQUESTED",
    "BROWSE_RESOURCES_RESULT",
    "BROWSE_RESOURCE_FAILED",
    "BROWSE_RESOURCE_OPEN",
    "BROWSE_RESOURCE_REQUESTED",
    "BROWSE_RESOURCE_RESULT",
    "BROWSE_RESOURCE_VIEWED",
    "BROWSE_TAG_SCHEMAS_FAILED",
    "BROWSE_TAG_SCHEMAS_REQUESTED",
    "BROWSE_TAG_SCHEMAS_RESULT",
    "BUS_RESUME_GAP",
    "FRAME_ADD_ENTITY_TYPE",
    "FRAME_ADD_TAG_SCHEMA",
    "FRAME_ENTITY_TYPE_ADDED",
    "FRAME_ENTITY_TYPE_ADD_FAILED",
    "FRAME_ENTITY_TYPE_ADD_OK",
    "FRAME_TAG_SCHEMA_ADDED",
    "FRAME_TAG_SCHEMA_ADD_FAILED",
    "FRAME_TAG_SCHEMA_ADD_OK",
    "GATHER_COMPLETE",
    "GATHER_FAILED",
    "GATHER_LIMITS_FAILED",
    "GATHER_LIMITS_REQUESTED",
    "GATHER_LIMITS_RESULT",
    "GATHER_REFERENCED_BY_FAILED",
    "GATHER_REFERENCED_BY_REQUESTED",
    "GATHER_REFERENCED_BY_RESULT",
    "GATHER_REQUESTED",
    "GATHER_RESOURCE_COMPLETE",
    "GATHER_RESOURCE_FAILED",
    "GATHER_RESOURCE_REQUESTED",
    "GATHER_SUMMARY_FAILED",
    "GATHER_SUMMARY_REQUESTED",
    "GATHER_SUMMARY_RESULT",
    "JOB_ASSIGN",
    "JOB_ASSIGNED",
    "JOB_CANCEL",
    "JOB_CANCEL_FAILED",
    "JOB_CANCEL_OK",
    "JOB_CANCEL_REQUESTED",
    "JOB_CHECKPOINT",
    "JOB_CLAIM",
    "JOB_CLAIMED",
    "JOB_CLAIM_FAILED",
    "JOB_COMPLETE",
    "JOB_COMPLETED",
    "JOB_CREATE",
    "JOB_CREATED",
    "JOB_CREATE_FAILED",
    "JOB_FAIL",
    "JOB_FAILED",
    "JOB_LIMITS_FAILED",
    "JOB_LIMITS_REQUESTED",
    "JOB_LIMITS_RESULT",
    "JOB_QUEUED",
    "JOB_REPORT_PROGRESS",
    "JOB_START",
    "JOB_STARTED",
    "JOB_STATUS_FAILED",
    "JOB_STATUS_REQUESTED",
    "JOB_STATUS_RESULT",
    "MARK_ADDED",
    "MARK_ARCHIVE",
    "MARK_ARCHIVED",
    "MARK_ARCHIVE_FAILED",
    "MARK_ARCHIVE_OK",
    "MARK_BODY_UPDATED",
    "MARK_BODY_UPDATE_FAILED",
    "MARK_CANCEL_PENDING",
    "MARK_COMMIT",
    "MARK_COMMIT_FAILED",
    "MARK_COMMIT_OK",
    "MARK_CREATE",
    "MARK_CREATE_ERROR",
    "MARK_CREATE_FAILED",
    "MARK_CREATE_OK",
    "MARK_CREATE_REQUEST",
    "MARK_DELEGATE_REQUEST",
    "MARK_DELEGATE_TIMEOUT",
    "MARK_DELETE",
    "MARK_DELETE_ERROR",
    "MARK_DELETE_FAILED",
    "MARK_DELETE_OK",
    "MARK_ENTITY_TAG_ADDED",
    "MARK_ENTITY_TAG_REMOVED",
    "MARK_PROGRESS_DISMISS",
    "MARK_REMOVED",
    "MARK_REQUESTED",
    "MARK_SELECT_ASSESSMENT",
    "MARK_SELECT_COMMENT",
    "MARK_SELECT_REFERENCE",
    "MARK_SELECT_TAG",
    "MARK_SUBMIT",
    "MARK_UNARCHIVE",
    "MARK_UNARCHIVED",
    "MARK_UNARCHIVE_FAILED",
    "MARK_UNARCHIVE_OK",
    "MARK_UPDATE_BODY",
    "MARK_UPDATE_ENTITY_TYPES",
    "MARK_UPDATE_ENTITY_TYPES_FAILED",
    "MARK_UPDATE_ENTITY_TYPES_OK",
    "MATCH_LIMITS_FAILED",
    "MATCH_LIMITS_REQUESTED",
    "MATCH_LIMITS_RESULT",
    "MATCH_RESOURCES_FAILED",
    "MATCH_RESOURCES_REQUESTED",
    "MATCH_RESOURCES_RESULT",
    "MATCH_SEARCH_FAILED",
    "MATCH_SEARCH_REQUESTED",
    "MATCH_SEARCH_RESULTS",
    "NAV_EXTERNAL",
    "NAV_LINK_CLICKED",
    "NAV_PUSH",
    "PANEL_CLOSE",
    "PANEL_OPEN",
    "PANEL_TOGGLE",
    "PERSON_PROFILE",
    "PERSON_PROFILED",
    "SESSION_JOINED",
    "SESSION_LEFT",
    "SETTINGS_HOVER_DELAY_CHANGED",
    "SETTINGS_LINE_NUMBERS_TOGGLED",
    "SETTINGS_LOCALE_CHANGED",
    "SETTINGS_THEME_CHANGED",
    "SHELL_SIDEBAR_TOGGLE",
    "SMELT_REBUILD_ANCHORS",
    "SMELT_REBUILD_ANCHORS_FAILED",
    "SMELT_REBUILD_ANCHORS_OK",
    "SMELT_SETTLED",
    "TABS_CLOSE",
    "TABS_REORDER",
    "WEAVE_APPLIED",
    "WEAVE_REBUILD",
    "WEAVE_REBUILD_FAILED",
    "WEAVE_REBUILD_OK",
    "YIELD_CLONE",
    "YIELD_CLONED",
    "YIELD_CLONE_CREATE",
    "YIELD_CLONE_CREATED",
    "YIELD_CLONE_CREATE_FAILED",
    "YIELD_CLONE_PERSIST",
    "YIELD_CLONE_PERSIST_FAILED",
    "YIELD_CLONE_PERSIST_OK",
    "YIELD_CLONE_RESOURCE_FAILED",
    "YIELD_CLONE_RESOURCE_REQUESTED",
    "YIELD_CLONE_RESOURCE_RESULT",
    "YIELD_CLONE_TOKEN_FAILED",
    "YIELD_CLONE_TOKEN_GENERATED",
    "YIELD_CLONE_TOKEN_REQUESTED",
    "YIELD_CREATE",
    "YIELD_CREATED",
    "YIELD_CREATE_FAILED",
    "YIELD_CREATE_OK",
    "YIELD_MOVED",
    "YIELD_MOVE_FAILED",
    "YIELD_MV",
    "YIELD_REPRESENTATION_ADDED",
    "YIELD_REPRESENTATION_REMOVED",
    "YIELD_UPDATE",
    "YIELD_UPDATED",
    "YIELD_UPDATE_FAILED",
    "YIELD_UPDATE_OK",
    "ChannelName",
]

# Every channel's name.
type ChannelName = Literal[
    "yield:created",
    "yield:cloned",
    "yield:updated",
    "yield:moved",
    "yield:representation-added",
    "yield:representation-removed",
    "yield:create",
    "yield:clone-persist",
    "yield:update",
    "yield:mv",
    "yield:clone",
    "yield:clone-token-requested",
    "yield:clone-resource-requested",
    "yield:clone-create",
    "yield:create-ok",
    "yield:create-failed",
    "yield:clone-persist-ok",
    "yield:clone-persist-failed",
    "yield:update-ok",
    "yield:update-failed",
    "yield:move-failed",
    "yield:clone-token-generated",
    "yield:clone-token-failed",
    "yield:clone-resource-result",
    "yield:clone-resource-failed",
    "yield:clone-created",
    "yield:clone-create-failed",
    "mark:added",
    "mark:removed",
    "mark:body-updated",
    "mark:entity-tag-added",
    "mark:entity-tag-removed",
    "mark:archived",
    "mark:unarchived",
    "mark:create-request",
    "mark:create",
    "mark:delete",
    "mark:update-body",
    "mark:archive",
    "mark:unarchive",
    "mark:update-entity-types",
    "mark:create-ok",
    "mark:create-failed",
    "mark:commit",
    "mark:commit-ok",
    "mark:commit-failed",
    "mark:delete-ok",
    "mark:delete-failed",
    "mark:archive-ok",
    "mark:archive-failed",
    "mark:unarchive-ok",
    "mark:unarchive-failed",
    "mark:update-entity-types-ok",
    "mark:update-entity-types-failed",
    "mark:body-update-failed",
    "mark:select-comment",
    "mark:select-tag",
    "mark:select-assessment",
    "mark:select-reference",
    "mark:requested",
    "mark:cancel-pending",
    "mark:submit",
    "mark:delegate-request",
    "mark:progress-dismiss",
    "mark:delegate-timeout",
    "mark:create-error",
    "mark:delete-error",
    "bind:body-error",
    "frame:entity-type-added",
    "frame:tag-schema-added",
    "frame:add-entity-type",
    "frame:add-tag-schema",
    "frame:entity-type-add-ok",
    "frame:entity-type-add-failed",
    "frame:tag-schema-add-ok",
    "frame:tag-schema-add-failed",
    "person:profiled",
    "person:profile",
    "bind:initiate",
    "bind:update-body",
    "bind:body-updated",
    "bind:body-update-failed",
    "match:search-requested",
    "match:search-results",
    "match:search-failed",
    "match:resources-requested",
    "match:resources-result",
    "match:resources-failed",
    "match:limits-requested",
    "match:limits-result",
    "match:limits-failed",
    "gather:requested",
    "gather:complete",
    "gather:failed",
    "gather:resource-requested",
    "gather:resource-complete",
    "gather:resource-failed",
    "gather:summary-requested",
    "gather:summary-result",
    "gather:summary-failed",
    "gather:referenced-by-requested",
    "gather:referenced-by-result",
    "gather:referenced-by-failed",
    "gather:limits-requested",
    "gather:limits-result",
    "gather:limits-failed",
    "browse:resource-requested",
    "browse:resource-result",
    "browse:resource-failed",
    "browse:anchored-text-requested",
    "browse:anchored-text-result",
    "browse:anchored-text-failed",
    "browse:resources-requested",
    "browse:resources-result",
    "browse:resources-failed",
    "browse:annotations-requested",
    "browse:annotations-result",
    "browse:annotations-failed",
    "browse:annotation-requested",
    "browse:annotation-result",
    "browse:annotation-failed",
    "browse:events-requested",
    "browse:events-result",
    "browse:events-failed",
    "browse:annotation-history-requested",
    "browse:annotation-history-result",
    "browse:annotation-history-failed",
    "browse:entity-types-requested",
    "browse:entity-types-result",
    "browse:entity-types-failed",
    "browse:tag-schemas-requested",
    "browse:tag-schemas-result",
    "browse:tag-schemas-failed",
    "browse:agents-requested",
    "browse:agents-result",
    "browse:agents-failed",
    "browse:kb-requested",
    "browse:kb-result",
    "browse:kb-failed",
    "browse:directory-requested",
    "browse:directory-result",
    "browse:directory-failed",
    "browse:click",
    "browse:resource-open",
    "browse:resource-viewed",
    "browse:entity-type-clicked",
    "panel:toggle",
    "panel:open",
    "panel:close",
    "shell:sidebar-toggle",
    "tabs:close",
    "tabs:reorder",
    "nav:link-clicked",
    "nav:push",
    "nav:external",
    "beckon:hover",
    "beckon:focus",
    "beckon:sparkle",
    "job:started",
    "job:assigned",
    "job:completed",
    "job:failed",
    "job:start",
    "job:assign",
    "job:report-progress",
    "job:complete",
    "job:fail",
    "job:checkpoint",
    "job:queued",
    "job:cancel-requested",
    "job:cancel",
    "job:limits-requested",
    "job:limits-result",
    "job:limits-failed",
    "job:status-requested",
    "job:create",
    "job:claim",
    "job:status-result",
    "job:status-failed",
    "job:created",
    "job:create-failed",
    "job:claimed",
    "job:claim-failed",
    "job:cancel-ok",
    "job:cancel-failed",
    "weave:applied",
    "smelt:settled",
    "weave:rebuild",
    "weave:rebuild-ok",
    "weave:rebuild-failed",
    "smelt:rebuild-anchors",
    "smelt:rebuild-anchors-ok",
    "smelt:rebuild-anchors-failed",
    "settings:theme-changed",
    "settings:line-numbers-toggled",
    "settings:locale-changed",
    "settings:hover-delay-changed",
    "bus:resume-gap",
    "session:joined",
    "session:left",
]

CHANNEL_NAMES: Final[tuple[ChannelName, ...]] = (
    "yield:created",
    "yield:cloned",
    "yield:updated",
    "yield:moved",
    "yield:representation-added",
    "yield:representation-removed",
    "yield:create",
    "yield:clone-persist",
    "yield:update",
    "yield:mv",
    "yield:clone",
    "yield:clone-token-requested",
    "yield:clone-resource-requested",
    "yield:clone-create",
    "yield:create-ok",
    "yield:create-failed",
    "yield:clone-persist-ok",
    "yield:clone-persist-failed",
    "yield:update-ok",
    "yield:update-failed",
    "yield:move-failed",
    "yield:clone-token-generated",
    "yield:clone-token-failed",
    "yield:clone-resource-result",
    "yield:clone-resource-failed",
    "yield:clone-created",
    "yield:clone-create-failed",
    "mark:added",
    "mark:removed",
    "mark:body-updated",
    "mark:entity-tag-added",
    "mark:entity-tag-removed",
    "mark:archived",
    "mark:unarchived",
    "mark:create-request",
    "mark:create",
    "mark:delete",
    "mark:update-body",
    "mark:archive",
    "mark:unarchive",
    "mark:update-entity-types",
    "mark:create-ok",
    "mark:create-failed",
    "mark:commit",
    "mark:commit-ok",
    "mark:commit-failed",
    "mark:delete-ok",
    "mark:delete-failed",
    "mark:archive-ok",
    "mark:archive-failed",
    "mark:unarchive-ok",
    "mark:unarchive-failed",
    "mark:update-entity-types-ok",
    "mark:update-entity-types-failed",
    "mark:body-update-failed",
    "mark:select-comment",
    "mark:select-tag",
    "mark:select-assessment",
    "mark:select-reference",
    "mark:requested",
    "mark:cancel-pending",
    "mark:submit",
    "mark:delegate-request",
    "mark:progress-dismiss",
    "mark:delegate-timeout",
    "mark:create-error",
    "mark:delete-error",
    "bind:body-error",
    "frame:entity-type-added",
    "frame:tag-schema-added",
    "frame:add-entity-type",
    "frame:add-tag-schema",
    "frame:entity-type-add-ok",
    "frame:entity-type-add-failed",
    "frame:tag-schema-add-ok",
    "frame:tag-schema-add-failed",
    "person:profiled",
    "person:profile",
    "bind:initiate",
    "bind:update-body",
    "bind:body-updated",
    "bind:body-update-failed",
    "match:search-requested",
    "match:search-results",
    "match:search-failed",
    "match:resources-requested",
    "match:resources-result",
    "match:resources-failed",
    "match:limits-requested",
    "match:limits-result",
    "match:limits-failed",
    "gather:requested",
    "gather:complete",
    "gather:failed",
    "gather:resource-requested",
    "gather:resource-complete",
    "gather:resource-failed",
    "gather:summary-requested",
    "gather:summary-result",
    "gather:summary-failed",
    "gather:referenced-by-requested",
    "gather:referenced-by-result",
    "gather:referenced-by-failed",
    "gather:limits-requested",
    "gather:limits-result",
    "gather:limits-failed",
    "browse:resource-requested",
    "browse:resource-result",
    "browse:resource-failed",
    "browse:anchored-text-requested",
    "browse:anchored-text-result",
    "browse:anchored-text-failed",
    "browse:resources-requested",
    "browse:resources-result",
    "browse:resources-failed",
    "browse:annotations-requested",
    "browse:annotations-result",
    "browse:annotations-failed",
    "browse:annotation-requested",
    "browse:annotation-result",
    "browse:annotation-failed",
    "browse:events-requested",
    "browse:events-result",
    "browse:events-failed",
    "browse:annotation-history-requested",
    "browse:annotation-history-result",
    "browse:annotation-history-failed",
    "browse:entity-types-requested",
    "browse:entity-types-result",
    "browse:entity-types-failed",
    "browse:tag-schemas-requested",
    "browse:tag-schemas-result",
    "browse:tag-schemas-failed",
    "browse:agents-requested",
    "browse:agents-result",
    "browse:agents-failed",
    "browse:kb-requested",
    "browse:kb-result",
    "browse:kb-failed",
    "browse:directory-requested",
    "browse:directory-result",
    "browse:directory-failed",
    "browse:click",
    "browse:resource-open",
    "browse:resource-viewed",
    "browse:entity-type-clicked",
    "panel:toggle",
    "panel:open",
    "panel:close",
    "shell:sidebar-toggle",
    "tabs:close",
    "tabs:reorder",
    "nav:link-clicked",
    "nav:push",
    "nav:external",
    "beckon:hover",
    "beckon:focus",
    "beckon:sparkle",
    "job:started",
    "job:assigned",
    "job:completed",
    "job:failed",
    "job:start",
    "job:assign",
    "job:report-progress",
    "job:complete",
    "job:fail",
    "job:checkpoint",
    "job:queued",
    "job:cancel-requested",
    "job:cancel",
    "job:limits-requested",
    "job:limits-result",
    "job:limits-failed",
    "job:status-requested",
    "job:create",
    "job:claim",
    "job:status-result",
    "job:status-failed",
    "job:created",
    "job:create-failed",
    "job:claimed",
    "job:claim-failed",
    "job:cancel-ok",
    "job:cancel-failed",
    "weave:applied",
    "smelt:settled",
    "weave:rebuild",
    "weave:rebuild-ok",
    "weave:rebuild-failed",
    "smelt:rebuild-anchors",
    "smelt:rebuild-anchors-ok",
    "smelt:rebuild-anchors-failed",
    "settings:theme-changed",
    "settings:line-numbers-toggled",
    "settings:locale-changed",
    "settings:hover-delay-changed",
    "bus:resume-gap",
    "session:joined",
    "session:left",
)

YIELD_CREATED: Final = Channel[StoredEventResponse]("yield:created", StoredEventResponse)
YIELD_CLONED: Final = Channel[StoredEventResponse]("yield:cloned", StoredEventResponse)
YIELD_UPDATED: Final = Channel[StoredEventResponse]("yield:updated", StoredEventResponse)
YIELD_MOVED: Final = Channel[StoredEventResponse]("yield:moved", StoredEventResponse)
YIELD_REPRESENTATION_ADDED: Final = ScopedChannel[StoredEventResponse]("yield:representation-added", StoredEventResponse)
YIELD_REPRESENTATION_REMOVED: Final = ScopedChannel[StoredEventResponse]("yield:representation-removed", StoredEventResponse)
YIELD_CREATE: Final = Channel[YieldCreateCommand]("yield:create", YieldCreateCommand)
YIELD_CLONE_PERSIST: Final = Channel[YieldClonePersistCommand]("yield:clone-persist", YieldClonePersistCommand)
YIELD_UPDATE: Final = Channel[YieldUpdateCommand]("yield:update", YieldUpdateCommand)
YIELD_MV: Final = Channel[YieldMvCommand]("yield:mv", YieldMvCommand)
YIELD_CLONE: Final = Channel[Empty]("yield:clone", Empty)
YIELD_CLONE_TOKEN_REQUESTED: Final = Channel[YieldCloneTokenRequest]("yield:clone-token-requested", YieldCloneTokenRequest)
YIELD_CLONE_RESOURCE_REQUESTED: Final = Channel[YieldCloneResourceRequest]("yield:clone-resource-requested", YieldCloneResourceRequest)
YIELD_CLONE_CREATE: Final = Channel[YieldCloneCreateCommand]("yield:clone-create", YieldCloneCreateCommand)
YIELD_CREATE_OK: Final = Channel[YieldCreateOk]("yield:create-ok", YieldCreateOk)
YIELD_CREATE_FAILED: Final = Channel[CommandError]("yield:create-failed", CommandError)
YIELD_CLONE_PERSIST_OK: Final = Channel[YieldClonePersistOk]("yield:clone-persist-ok", YieldClonePersistOk)
YIELD_CLONE_PERSIST_FAILED: Final = Channel[CommandError]("yield:clone-persist-failed", CommandError)
YIELD_UPDATE_OK: Final = Channel[YieldUpdateOk]("yield:update-ok", YieldUpdateOk)
YIELD_UPDATE_FAILED: Final = Channel[CommandError]("yield:update-failed", CommandError)
YIELD_MOVE_FAILED: Final = Channel[YieldMoveFailed]("yield:move-failed", YieldMoveFailed)
YIELD_CLONE_TOKEN_GENERATED: Final = Channel[Response[CloneResourceWithTokenResponse]]("yield:clone-token-generated", Response[CloneResourceWithTokenResponse])
YIELD_CLONE_TOKEN_FAILED: Final = Channel[CommandError]("yield:clone-token-failed", CommandError)
YIELD_CLONE_RESOURCE_RESULT: Final = Channel[Response[GetResourceByTokenResponse]]("yield:clone-resource-result", Response[GetResourceByTokenResponse])
YIELD_CLONE_RESOURCE_FAILED: Final = Channel[CommandError]("yield:clone-resource-failed", CommandError)
YIELD_CLONE_CREATED: Final = Channel[YieldCloneCreated]("yield:clone-created", YieldCloneCreated)
YIELD_CLONE_CREATE_FAILED: Final = Channel[CommandError]("yield:clone-create-failed", CommandError)
MARK_ADDED: Final = ScopedChannel[EnrichedResourceEvent]("mark:added", EnrichedResourceEvent)
MARK_REMOVED: Final = ScopedChannel[StoredEventResponse]("mark:removed", StoredEventResponse)
MARK_BODY_UPDATED: Final = ScopedChannel[EnrichedResourceEvent]("mark:body-updated", EnrichedResourceEvent)
MARK_ENTITY_TAG_ADDED: Final = ScopedChannel[StoredEventResponse]("mark:entity-tag-added", StoredEventResponse)
MARK_ENTITY_TAG_REMOVED: Final = ScopedChannel[StoredEventResponse]("mark:entity-tag-removed", StoredEventResponse)
MARK_ARCHIVED: Final = ScopedChannel[StoredEventResponse]("mark:archived", StoredEventResponse)
MARK_UNARCHIVED: Final = ScopedChannel[StoredEventResponse]("mark:unarchived", StoredEventResponse)
MARK_CREATE_REQUEST: Final = Channel[MarkCreateRequest]("mark:create-request", MarkCreateRequest)
MARK_CREATE: Final = Channel[MarkCreateCommand]("mark:create", MarkCreateCommand)
MARK_DELETE: Final = Channel[MarkDeleteCommand]("mark:delete", MarkDeleteCommand)
MARK_UPDATE_BODY: Final = Channel[MarkUpdateBodyCommand]("mark:update-body", MarkUpdateBodyCommand)
MARK_ARCHIVE: Final = Channel[MarkArchiveCommand]("mark:archive", MarkArchiveCommand)
MARK_UNARCHIVE: Final = Channel[MarkUnarchiveCommand]("mark:unarchive", MarkUnarchiveCommand)
MARK_UPDATE_ENTITY_TYPES: Final = Channel[MarkUpdateEntityTypesCommand]("mark:update-entity-types", MarkUpdateEntityTypesCommand)
MARK_CREATE_OK: Final = Channel[MarkCreateOk]("mark:create-ok", MarkCreateOk)
MARK_CREATE_FAILED: Final = Channel[CommandError]("mark:create-failed", CommandError)
MARK_COMMIT: Final = Channel[MarkCommitCommand]("mark:commit", MarkCommitCommand)
MARK_COMMIT_OK: Final = Channel[MarkCommitOk]("mark:commit-ok", MarkCommitOk)
MARK_COMMIT_FAILED: Final = Channel[CommandError]("mark:commit-failed", CommandError)
MARK_DELETE_OK: Final = Channel[MarkDeleteOk]("mark:delete-ok", MarkDeleteOk)
MARK_DELETE_FAILED: Final = Channel[CommandError]("mark:delete-failed", CommandError)
MARK_ARCHIVE_OK: Final = Channel[Empty]("mark:archive-ok", Empty)
MARK_ARCHIVE_FAILED: Final = Channel[CommandError]("mark:archive-failed", CommandError)
MARK_UNARCHIVE_OK: Final = Channel[Empty]("mark:unarchive-ok", Empty)
MARK_UNARCHIVE_FAILED: Final = Channel[CommandError]("mark:unarchive-failed", CommandError)
MARK_UPDATE_ENTITY_TYPES_OK: Final = Channel[Empty]("mark:update-entity-types-ok", Empty)
MARK_UPDATE_ENTITY_TYPES_FAILED: Final = Channel[CommandError]("mark:update-entity-types-failed", CommandError)
MARK_BODY_UPDATE_FAILED: Final = Channel[CommandError]("mark:body-update-failed", CommandError)
MARK_SELECT_COMMENT: Final = Channel[SelectionData]("mark:select-comment", SelectionData)
MARK_SELECT_TAG: Final = Channel[SelectionData]("mark:select-tag", SelectionData)
MARK_SELECT_ASSESSMENT: Final = Channel[SelectionData]("mark:select-assessment", SelectionData)
MARK_SELECT_REFERENCE: Final = Channel[SelectionData]("mark:select-reference", SelectionData)
MARK_REQUESTED: Final = Channel[MarkRequestedEvent]("mark:requested", MarkRequestedEvent)
MARK_CANCEL_PENDING: Final = Channel[Empty]("mark:cancel-pending", Empty)
MARK_SUBMIT: Final = Channel[MarkSubmitEvent]("mark:submit", MarkSubmitEvent)
MARK_DELEGATE_REQUEST: Final = Channel[MarkDelegateRequestEvent]("mark:delegate-request", MarkDelegateRequestEvent)
MARK_PROGRESS_DISMISS: Final = Channel[Empty]("mark:progress-dismiss", Empty)
MARK_DELEGATE_TIMEOUT: Final = Channel[MarkDelegateTimeoutEvent]("mark:delegate-timeout", MarkDelegateTimeoutEvent)
MARK_CREATE_ERROR: Final = Channel[ResourceErrorEvent]("mark:create-error", ResourceErrorEvent)
MARK_DELETE_ERROR: Final = Channel[ResourceErrorEvent]("mark:delete-error", ResourceErrorEvent)
BIND_BODY_ERROR: Final = Channel[ResourceErrorEvent]("bind:body-error", ResourceErrorEvent)
FRAME_ENTITY_TYPE_ADDED: Final = Channel[StoredEventResponse]("frame:entity-type-added", StoredEventResponse)
FRAME_TAG_SCHEMA_ADDED: Final = Channel[StoredEventResponse]("frame:tag-schema-added", StoredEventResponse)
FRAME_ADD_ENTITY_TYPE: Final = Channel[FrameAddEntityTypeCommand]("frame:add-entity-type", FrameAddEntityTypeCommand)
FRAME_ADD_TAG_SCHEMA: Final = Channel[FrameAddTagSchemaCommand]("frame:add-tag-schema", FrameAddTagSchemaCommand)
FRAME_ENTITY_TYPE_ADD_OK: Final = Channel[Empty]("frame:entity-type-add-ok", Empty)
FRAME_ENTITY_TYPE_ADD_FAILED: Final = Channel[CommandError]("frame:entity-type-add-failed", CommandError)
FRAME_TAG_SCHEMA_ADD_OK: Final = Channel[Empty]("frame:tag-schema-add-ok", Empty)
FRAME_TAG_SCHEMA_ADD_FAILED: Final = Channel[CommandError]("frame:tag-schema-add-failed", CommandError)
PERSON_PROFILED: Final = Channel[StoredEventResponse]("person:profiled", StoredEventResponse)
PERSON_PROFILE: Final = Channel[PersonProfileCommand]("person:profile", PersonProfileCommand)
BIND_INITIATE: Final = Channel[BindInitiateCommand]("bind:initiate", BindInitiateCommand)
BIND_UPDATE_BODY: Final = Channel[BindUpdateBodyCommand]("bind:update-body", BindUpdateBodyCommand)
BIND_BODY_UPDATED: Final = Channel[BindBodyUpdated]("bind:body-updated", BindBodyUpdated)
BIND_BODY_UPDATE_FAILED: Final = Channel[CommandError]("bind:body-update-failed", CommandError)
MATCH_SEARCH_REQUESTED: Final = Channel[MatchSearchRequest]("match:search-requested", MatchSearchRequest)
MATCH_SEARCH_RESULTS: Final = Channel[MatchSearchResult]("match:search-results", MatchSearchResult)
MATCH_SEARCH_FAILED: Final = Channel[MatchSearchFailed]("match:search-failed", MatchSearchFailed)
MATCH_RESOURCES_REQUESTED: Final = Channel[MatchResourcesRequest]("match:resources-requested", MatchResourcesRequest)
MATCH_RESOURCES_RESULT: Final = Channel[MatchResourcesResult]("match:resources-result", MatchResourcesResult)
MATCH_RESOURCES_FAILED: Final = Channel[CommandError]("match:resources-failed", CommandError)
MATCH_LIMITS_REQUESTED: Final = Channel[InferenceLimitsRequest]("match:limits-requested", InferenceLimitsRequest)
MATCH_LIMITS_RESULT: Final = Channel[InferenceLimitsResult]("match:limits-result", InferenceLimitsResult)
MATCH_LIMITS_FAILED: Final = Channel[CommandError]("match:limits-failed", CommandError)
GATHER_REQUESTED: Final = Channel[GatherAnnotationRequest]("gather:requested", GatherAnnotationRequest)
GATHER_COMPLETE: Final = Channel[GatherAnnotationComplete]("gather:complete", GatherAnnotationComplete)
GATHER_FAILED: Final = Channel[GatherFailed]("gather:failed", GatherFailed)
GATHER_RESOURCE_REQUESTED: Final = Channel[GatherResourceRequest]("gather:resource-requested", GatherResourceRequest)
GATHER_RESOURCE_COMPLETE: Final = Channel[GatherResourceComplete]("gather:resource-complete", GatherResourceComplete)
GATHER_RESOURCE_FAILED: Final = Channel[GatherResourceFailed]("gather:resource-failed", GatherResourceFailed)
GATHER_SUMMARY_REQUESTED: Final = Channel[GatherSummaryRequest]("gather:summary-requested", GatherSummaryRequest)
GATHER_SUMMARY_RESULT: Final = Channel[Response[ContextualSummaryResponse]]("gather:summary-result", Response[ContextualSummaryResponse])
GATHER_SUMMARY_FAILED: Final = Channel[CommandError]("gather:summary-failed", CommandError)
GATHER_REFERENCED_BY_REQUESTED: Final = Channel[GatherReferencedByRequest]("gather:referenced-by-requested", GatherReferencedByRequest)
GATHER_REFERENCED_BY_RESULT: Final = Channel[GatherReferencedByResult]("gather:referenced-by-result", GatherReferencedByResult)
GATHER_REFERENCED_BY_FAILED: Final = Channel[CommandError]("gather:referenced-by-failed", CommandError)
GATHER_LIMITS_REQUESTED: Final = Channel[InferenceLimitsRequest]("gather:limits-requested", InferenceLimitsRequest)
GATHER_LIMITS_RESULT: Final = Channel[InferenceLimitsResult]("gather:limits-result", InferenceLimitsResult)
GATHER_LIMITS_FAILED: Final = Channel[CommandError]("gather:limits-failed", CommandError)
BROWSE_RESOURCE_REQUESTED: Final = Channel[BrowseResourceRequest]("browse:resource-requested", BrowseResourceRequest)
BROWSE_RESOURCE_RESULT: Final = Channel[BrowseResourceResult]("browse:resource-result", BrowseResourceResult)
BROWSE_RESOURCE_FAILED: Final = Channel[CommandError]("browse:resource-failed", CommandError)
BROWSE_ANCHORED_TEXT_REQUESTED: Final = Channel[BrowseAnchoredTextRequest]("browse:anchored-text-requested", BrowseAnchoredTextRequest)
BROWSE_ANCHORED_TEXT_RESULT: Final = Channel[BrowseAnchoredTextResult]("browse:anchored-text-result", BrowseAnchoredTextResult)
BROWSE_ANCHORED_TEXT_FAILED: Final = Channel[CommandError]("browse:anchored-text-failed", CommandError)
BROWSE_RESOURCES_REQUESTED: Final = Channel[BrowseResourcesRequest]("browse:resources-requested", BrowseResourcesRequest)
BROWSE_RESOURCES_RESULT: Final = Channel[BrowseResourcesResult]("browse:resources-result", BrowseResourcesResult)
BROWSE_RESOURCES_FAILED: Final = Channel[CommandError]("browse:resources-failed", CommandError)
BROWSE_ANNOTATIONS_REQUESTED: Final = Channel[BrowseAnnotationsRequest]("browse:annotations-requested", BrowseAnnotationsRequest)
BROWSE_ANNOTATIONS_RESULT: Final = Channel[BrowseAnnotationsResult]("browse:annotations-result", BrowseAnnotationsResult)
BROWSE_ANNOTATIONS_FAILED: Final = Channel[CommandError]("browse:annotations-failed", CommandError)
BROWSE_ANNOTATION_REQUESTED: Final = Channel[BrowseAnnotationRequest]("browse:annotation-requested", BrowseAnnotationRequest)
BROWSE_ANNOTATION_RESULT: Final = Channel[BrowseAnnotationResult]("browse:annotation-result", BrowseAnnotationResult)
BROWSE_ANNOTATION_FAILED: Final = Channel[CommandError]("browse:annotation-failed", CommandError)
BROWSE_EVENTS_REQUESTED: Final = Channel[BrowseEventsRequest]("browse:events-requested", BrowseEventsRequest)
BROWSE_EVENTS_RESULT: Final = Channel[BrowseEventsResult]("browse:events-result", BrowseEventsResult)
BROWSE_EVENTS_FAILED: Final = Channel[CommandError]("browse:events-failed", CommandError)
BROWSE_ANNOTATION_HISTORY_REQUESTED: Final = Channel[BrowseAnnotationHistoryRequest]("browse:annotation-history-requested", BrowseAnnotationHistoryRequest)
BROWSE_ANNOTATION_HISTORY_RESULT: Final = Channel[BrowseAnnotationHistoryResult]("browse:annotation-history-result", BrowseAnnotationHistoryResult)
BROWSE_ANNOTATION_HISTORY_FAILED: Final = Channel[CommandError]("browse:annotation-history-failed", CommandError)
BROWSE_ENTITY_TYPES_REQUESTED: Final = Channel[BrowseEntityTypesRequest]("browse:entity-types-requested", BrowseEntityTypesRequest)
BROWSE_ENTITY_TYPES_RESULT: Final = Channel[BrowseEntityTypesResult]("browse:entity-types-result", BrowseEntityTypesResult)
BROWSE_ENTITY_TYPES_FAILED: Final = Channel[CommandError]("browse:entity-types-failed", CommandError)
BROWSE_TAG_SCHEMAS_REQUESTED: Final = Channel[BrowseTagSchemasRequest]("browse:tag-schemas-requested", BrowseTagSchemasRequest)
BROWSE_TAG_SCHEMAS_RESULT: Final = Channel[BrowseTagSchemasResult]("browse:tag-schemas-result", BrowseTagSchemasResult)
BROWSE_TAG_SCHEMAS_FAILED: Final = Channel[CommandError]("browse:tag-schemas-failed", CommandError)
BROWSE_AGENTS_REQUESTED: Final = Channel[BrowseAgentsRequest]("browse:agents-requested", BrowseAgentsRequest)
BROWSE_AGENTS_RESULT: Final = Channel[BrowseAgentsResult]("browse:agents-result", BrowseAgentsResult)
BROWSE_AGENTS_FAILED: Final = Channel[CommandError]("browse:agents-failed", CommandError)
BROWSE_KB_REQUESTED: Final = Channel[BrowseKbRequest]("browse:kb-requested", BrowseKbRequest)
BROWSE_KB_RESULT: Final = Channel[BrowseKbResult]("browse:kb-result", BrowseKbResult)
BROWSE_KB_FAILED: Final = Channel[CommandError]("browse:kb-failed", CommandError)
BROWSE_DIRECTORY_REQUESTED: Final = Channel[BrowseDirectoryRequest]("browse:directory-requested", BrowseDirectoryRequest)
BROWSE_DIRECTORY_RESULT: Final = Channel[BrowseDirectoryResult]("browse:directory-result", BrowseDirectoryResult)
BROWSE_DIRECTORY_FAILED: Final = Channel[BrowseDirectoryFailed]("browse:directory-failed", BrowseDirectoryFailed)
BROWSE_CLICK: Final = Channel[BrowseClickEvent]("browse:click", BrowseClickEvent)
BROWSE_RESOURCE_OPEN: Final = Channel[BrowseResourceOpenEvent]("browse:resource-open", BrowseResourceOpenEvent)
BROWSE_RESOURCE_VIEWED: Final = Channel[BrowseResourceViewedEvent]("browse:resource-viewed", BrowseResourceViewedEvent)
BROWSE_ENTITY_TYPE_CLICKED: Final = Channel[BrowseEntityTypeClickedEvent]("browse:entity-type-clicked", BrowseEntityTypeClickedEvent)
PANEL_TOGGLE: Final = Channel[BrowsePanelToggleEvent]("panel:toggle", BrowsePanelToggleEvent)
PANEL_OPEN: Final = Channel[BrowsePanelOpenEvent]("panel:open", BrowsePanelOpenEvent)
PANEL_CLOSE: Final = Channel[Empty]("panel:close", Empty)
SHELL_SIDEBAR_TOGGLE: Final = Channel[Empty]("shell:sidebar-toggle", Empty)
TABS_CLOSE: Final = Channel[BrowseResourceCloseEvent]("tabs:close", BrowseResourceCloseEvent)
TABS_REORDER: Final = Channel[BrowseResourceReorderEvent]("tabs:reorder", BrowseResourceReorderEvent)
NAV_LINK_CLICKED: Final = Channel[BrowseLinkClickedEvent]("nav:link-clicked", BrowseLinkClickedEvent)
NAV_PUSH: Final = Channel[BrowseRouterPushEvent]("nav:push", BrowseRouterPushEvent)
NAV_EXTERNAL: Final = Channel[BrowseExternalNavigateEvent]("nav:external", BrowseExternalNavigateEvent)
BECKON_HOVER: Final = Channel[BeckonHoverEvent]("beckon:hover", BeckonHoverEvent)
BECKON_FOCUS: Final = Channel[BeckonFocusEvent]("beckon:focus", BeckonFocusEvent)
BECKON_SPARKLE: Final = Channel[BeckonSparkleEvent]("beckon:sparkle", BeckonSparkleEvent)
JOB_STARTED: Final = ScopedChannel[StoredEventResponse]("job:started", StoredEventResponse)
JOB_ASSIGNED: Final = ScopedChannel[StoredEventResponse]("job:assigned", StoredEventResponse)
JOB_COMPLETED: Final = ScopedChannel[StoredEventResponse]("job:completed", StoredEventResponse)
JOB_FAILED: Final = ScopedChannel[StoredEventResponse]("job:failed", StoredEventResponse)
JOB_START: Final = Channel[JobStartCommand]("job:start", JobStartCommand)
JOB_ASSIGN: Final = Channel[JobAssignCommand]("job:assign", JobAssignCommand)
JOB_REPORT_PROGRESS: Final = Channel[JobReportProgressCommand]("job:report-progress", JobReportProgressCommand)
JOB_COMPLETE: Final = Channel[JobCompleteCommand]("job:complete", JobCompleteCommand)
JOB_FAIL: Final = Channel[JobFailCommand]("job:fail", JobFailCommand)
JOB_CHECKPOINT: Final = Channel[JobCheckpointCommand]("job:checkpoint", JobCheckpointCommand)
JOB_QUEUED: Final = Channel[JobQueuedEvent]("job:queued", JobQueuedEvent)
JOB_CANCEL_REQUESTED: Final = Channel[JobCancelRequest]("job:cancel-requested", JobCancelRequest)
JOB_CANCEL: Final = Channel[JobCancelCommand]("job:cancel", JobCancelCommand)
JOB_LIMITS_REQUESTED: Final = Channel[InferenceLimitsRequest]("job:limits-requested", InferenceLimitsRequest)
JOB_LIMITS_RESULT: Final = Channel[InferenceLimitsResult]("job:limits-result", InferenceLimitsResult)
JOB_LIMITS_FAILED: Final = Channel[CommandError]("job:limits-failed", CommandError)
JOB_STATUS_REQUESTED: Final = Channel[JobStatusRequest]("job:status-requested", JobStatusRequest)
JOB_CREATE: Final = Channel[JobCreateCommand]("job:create", JobCreateCommand)
JOB_CLAIM: Final = Channel[JobClaimCommand]("job:claim", JobClaimCommand)
JOB_STATUS_RESULT: Final = Channel[JobStatusResult]("job:status-result", JobStatusResult)
JOB_STATUS_FAILED: Final = Channel[CommandError]("job:status-failed", CommandError)
JOB_CREATED: Final = Channel[JobCreatedResult]("job:created", JobCreatedResult)
JOB_CREATE_FAILED: Final = Channel[CommandError]("job:create-failed", CommandError)
JOB_CLAIMED: Final = Channel[JobClaimedResult]("job:claimed", JobClaimedResult)
JOB_CLAIM_FAILED: Final = Channel[CommandError]("job:claim-failed", CommandError)
JOB_CANCEL_OK: Final = Channel[Response[JobCancelResult]]("job:cancel-ok", Response[JobCancelResult])
JOB_CANCEL_FAILED: Final = Channel[CommandError]("job:cancel-failed", CommandError)
WEAVE_APPLIED: Final = Channel[WeaveApplied]("weave:applied", WeaveApplied)
SMELT_SETTLED: Final = Channel[SmeltSettled]("smelt:settled", SmeltSettled)
WEAVE_REBUILD: Final = Channel[WeaveRebuildCommand]("weave:rebuild", WeaveRebuildCommand)
WEAVE_REBUILD_OK: Final = Channel[Empty]("weave:rebuild-ok", Empty)
WEAVE_REBUILD_FAILED: Final = Channel[CommandError]("weave:rebuild-failed", CommandError)
SMELT_REBUILD_ANCHORS: Final = Channel[SmeltRebuildAnchorsCommand]("smelt:rebuild-anchors", SmeltRebuildAnchorsCommand)
SMELT_REBUILD_ANCHORS_OK: Final = Channel[Empty]("smelt:rebuild-anchors-ok", Empty)
SMELT_REBUILD_ANCHORS_FAILED: Final = Channel[CommandError]("smelt:rebuild-anchors-failed", CommandError)
SETTINGS_THEME_CHANGED: Final = Channel[SettingsThemeChangedEvent]("settings:theme-changed", SettingsThemeChangedEvent)
SETTINGS_LINE_NUMBERS_TOGGLED: Final = Channel[Empty]("settings:line-numbers-toggled", Empty)
SETTINGS_LOCALE_CHANGED: Final = Channel[SettingsLocaleChangedEvent]("settings:locale-changed", SettingsLocaleChangedEvent)
SETTINGS_HOVER_DELAY_CHANGED: Final = Channel[SettingsHoverDelayChangedEvent]("settings:hover-delay-changed", SettingsHoverDelayChangedEvent)
BUS_RESUME_GAP: Final = Channel[BusResumeGap]("bus:resume-gap", BusResumeGap)
SESSION_JOINED: Final = Channel[SessionJoinedEvent]("session:joined", SessionJoinedEvent)
SESSION_LEFT: Final = Channel[SessionLeftEvent]("session:left", SessionLeftEvent)

# Every channel, by its name: for code that is given a name and not a constant.
CHANNELS: Final[Mapping[str, AnyChannel]] = MappingProxyType(
    {
        "yield:created": YIELD_CREATED,
        "yield:cloned": YIELD_CLONED,
        "yield:updated": YIELD_UPDATED,
        "yield:moved": YIELD_MOVED,
        "yield:representation-added": YIELD_REPRESENTATION_ADDED,
        "yield:representation-removed": YIELD_REPRESENTATION_REMOVED,
        "yield:create": YIELD_CREATE,
        "yield:clone-persist": YIELD_CLONE_PERSIST,
        "yield:update": YIELD_UPDATE,
        "yield:mv": YIELD_MV,
        "yield:clone": YIELD_CLONE,
        "yield:clone-token-requested": YIELD_CLONE_TOKEN_REQUESTED,
        "yield:clone-resource-requested": YIELD_CLONE_RESOURCE_REQUESTED,
        "yield:clone-create": YIELD_CLONE_CREATE,
        "yield:create-ok": YIELD_CREATE_OK,
        "yield:create-failed": YIELD_CREATE_FAILED,
        "yield:clone-persist-ok": YIELD_CLONE_PERSIST_OK,
        "yield:clone-persist-failed": YIELD_CLONE_PERSIST_FAILED,
        "yield:update-ok": YIELD_UPDATE_OK,
        "yield:update-failed": YIELD_UPDATE_FAILED,
        "yield:move-failed": YIELD_MOVE_FAILED,
        "yield:clone-token-generated": YIELD_CLONE_TOKEN_GENERATED,
        "yield:clone-token-failed": YIELD_CLONE_TOKEN_FAILED,
        "yield:clone-resource-result": YIELD_CLONE_RESOURCE_RESULT,
        "yield:clone-resource-failed": YIELD_CLONE_RESOURCE_FAILED,
        "yield:clone-created": YIELD_CLONE_CREATED,
        "yield:clone-create-failed": YIELD_CLONE_CREATE_FAILED,
        "mark:added": MARK_ADDED,
        "mark:removed": MARK_REMOVED,
        "mark:body-updated": MARK_BODY_UPDATED,
        "mark:entity-tag-added": MARK_ENTITY_TAG_ADDED,
        "mark:entity-tag-removed": MARK_ENTITY_TAG_REMOVED,
        "mark:archived": MARK_ARCHIVED,
        "mark:unarchived": MARK_UNARCHIVED,
        "mark:create-request": MARK_CREATE_REQUEST,
        "mark:create": MARK_CREATE,
        "mark:delete": MARK_DELETE,
        "mark:update-body": MARK_UPDATE_BODY,
        "mark:archive": MARK_ARCHIVE,
        "mark:unarchive": MARK_UNARCHIVE,
        "mark:update-entity-types": MARK_UPDATE_ENTITY_TYPES,
        "mark:create-ok": MARK_CREATE_OK,
        "mark:create-failed": MARK_CREATE_FAILED,
        "mark:commit": MARK_COMMIT,
        "mark:commit-ok": MARK_COMMIT_OK,
        "mark:commit-failed": MARK_COMMIT_FAILED,
        "mark:delete-ok": MARK_DELETE_OK,
        "mark:delete-failed": MARK_DELETE_FAILED,
        "mark:archive-ok": MARK_ARCHIVE_OK,
        "mark:archive-failed": MARK_ARCHIVE_FAILED,
        "mark:unarchive-ok": MARK_UNARCHIVE_OK,
        "mark:unarchive-failed": MARK_UNARCHIVE_FAILED,
        "mark:update-entity-types-ok": MARK_UPDATE_ENTITY_TYPES_OK,
        "mark:update-entity-types-failed": MARK_UPDATE_ENTITY_TYPES_FAILED,
        "mark:body-update-failed": MARK_BODY_UPDATE_FAILED,
        "mark:select-comment": MARK_SELECT_COMMENT,
        "mark:select-tag": MARK_SELECT_TAG,
        "mark:select-assessment": MARK_SELECT_ASSESSMENT,
        "mark:select-reference": MARK_SELECT_REFERENCE,
        "mark:requested": MARK_REQUESTED,
        "mark:cancel-pending": MARK_CANCEL_PENDING,
        "mark:submit": MARK_SUBMIT,
        "mark:delegate-request": MARK_DELEGATE_REQUEST,
        "mark:progress-dismiss": MARK_PROGRESS_DISMISS,
        "mark:delegate-timeout": MARK_DELEGATE_TIMEOUT,
        "mark:create-error": MARK_CREATE_ERROR,
        "mark:delete-error": MARK_DELETE_ERROR,
        "bind:body-error": BIND_BODY_ERROR,
        "frame:entity-type-added": FRAME_ENTITY_TYPE_ADDED,
        "frame:tag-schema-added": FRAME_TAG_SCHEMA_ADDED,
        "frame:add-entity-type": FRAME_ADD_ENTITY_TYPE,
        "frame:add-tag-schema": FRAME_ADD_TAG_SCHEMA,
        "frame:entity-type-add-ok": FRAME_ENTITY_TYPE_ADD_OK,
        "frame:entity-type-add-failed": FRAME_ENTITY_TYPE_ADD_FAILED,
        "frame:tag-schema-add-ok": FRAME_TAG_SCHEMA_ADD_OK,
        "frame:tag-schema-add-failed": FRAME_TAG_SCHEMA_ADD_FAILED,
        "person:profiled": PERSON_PROFILED,
        "person:profile": PERSON_PROFILE,
        "bind:initiate": BIND_INITIATE,
        "bind:update-body": BIND_UPDATE_BODY,
        "bind:body-updated": BIND_BODY_UPDATED,
        "bind:body-update-failed": BIND_BODY_UPDATE_FAILED,
        "match:search-requested": MATCH_SEARCH_REQUESTED,
        "match:search-results": MATCH_SEARCH_RESULTS,
        "match:search-failed": MATCH_SEARCH_FAILED,
        "match:resources-requested": MATCH_RESOURCES_REQUESTED,
        "match:resources-result": MATCH_RESOURCES_RESULT,
        "match:resources-failed": MATCH_RESOURCES_FAILED,
        "match:limits-requested": MATCH_LIMITS_REQUESTED,
        "match:limits-result": MATCH_LIMITS_RESULT,
        "match:limits-failed": MATCH_LIMITS_FAILED,
        "gather:requested": GATHER_REQUESTED,
        "gather:complete": GATHER_COMPLETE,
        "gather:failed": GATHER_FAILED,
        "gather:resource-requested": GATHER_RESOURCE_REQUESTED,
        "gather:resource-complete": GATHER_RESOURCE_COMPLETE,
        "gather:resource-failed": GATHER_RESOURCE_FAILED,
        "gather:summary-requested": GATHER_SUMMARY_REQUESTED,
        "gather:summary-result": GATHER_SUMMARY_RESULT,
        "gather:summary-failed": GATHER_SUMMARY_FAILED,
        "gather:referenced-by-requested": GATHER_REFERENCED_BY_REQUESTED,
        "gather:referenced-by-result": GATHER_REFERENCED_BY_RESULT,
        "gather:referenced-by-failed": GATHER_REFERENCED_BY_FAILED,
        "gather:limits-requested": GATHER_LIMITS_REQUESTED,
        "gather:limits-result": GATHER_LIMITS_RESULT,
        "gather:limits-failed": GATHER_LIMITS_FAILED,
        "browse:resource-requested": BROWSE_RESOURCE_REQUESTED,
        "browse:resource-result": BROWSE_RESOURCE_RESULT,
        "browse:resource-failed": BROWSE_RESOURCE_FAILED,
        "browse:anchored-text-requested": BROWSE_ANCHORED_TEXT_REQUESTED,
        "browse:anchored-text-result": BROWSE_ANCHORED_TEXT_RESULT,
        "browse:anchored-text-failed": BROWSE_ANCHORED_TEXT_FAILED,
        "browse:resources-requested": BROWSE_RESOURCES_REQUESTED,
        "browse:resources-result": BROWSE_RESOURCES_RESULT,
        "browse:resources-failed": BROWSE_RESOURCES_FAILED,
        "browse:annotations-requested": BROWSE_ANNOTATIONS_REQUESTED,
        "browse:annotations-result": BROWSE_ANNOTATIONS_RESULT,
        "browse:annotations-failed": BROWSE_ANNOTATIONS_FAILED,
        "browse:annotation-requested": BROWSE_ANNOTATION_REQUESTED,
        "browse:annotation-result": BROWSE_ANNOTATION_RESULT,
        "browse:annotation-failed": BROWSE_ANNOTATION_FAILED,
        "browse:events-requested": BROWSE_EVENTS_REQUESTED,
        "browse:events-result": BROWSE_EVENTS_RESULT,
        "browse:events-failed": BROWSE_EVENTS_FAILED,
        "browse:annotation-history-requested": BROWSE_ANNOTATION_HISTORY_REQUESTED,
        "browse:annotation-history-result": BROWSE_ANNOTATION_HISTORY_RESULT,
        "browse:annotation-history-failed": BROWSE_ANNOTATION_HISTORY_FAILED,
        "browse:entity-types-requested": BROWSE_ENTITY_TYPES_REQUESTED,
        "browse:entity-types-result": BROWSE_ENTITY_TYPES_RESULT,
        "browse:entity-types-failed": BROWSE_ENTITY_TYPES_FAILED,
        "browse:tag-schemas-requested": BROWSE_TAG_SCHEMAS_REQUESTED,
        "browse:tag-schemas-result": BROWSE_TAG_SCHEMAS_RESULT,
        "browse:tag-schemas-failed": BROWSE_TAG_SCHEMAS_FAILED,
        "browse:agents-requested": BROWSE_AGENTS_REQUESTED,
        "browse:agents-result": BROWSE_AGENTS_RESULT,
        "browse:agents-failed": BROWSE_AGENTS_FAILED,
        "browse:kb-requested": BROWSE_KB_REQUESTED,
        "browse:kb-result": BROWSE_KB_RESULT,
        "browse:kb-failed": BROWSE_KB_FAILED,
        "browse:directory-requested": BROWSE_DIRECTORY_REQUESTED,
        "browse:directory-result": BROWSE_DIRECTORY_RESULT,
        "browse:directory-failed": BROWSE_DIRECTORY_FAILED,
        "browse:click": BROWSE_CLICK,
        "browse:resource-open": BROWSE_RESOURCE_OPEN,
        "browse:resource-viewed": BROWSE_RESOURCE_VIEWED,
        "browse:entity-type-clicked": BROWSE_ENTITY_TYPE_CLICKED,
        "panel:toggle": PANEL_TOGGLE,
        "panel:open": PANEL_OPEN,
        "panel:close": PANEL_CLOSE,
        "shell:sidebar-toggle": SHELL_SIDEBAR_TOGGLE,
        "tabs:close": TABS_CLOSE,
        "tabs:reorder": TABS_REORDER,
        "nav:link-clicked": NAV_LINK_CLICKED,
        "nav:push": NAV_PUSH,
        "nav:external": NAV_EXTERNAL,
        "beckon:hover": BECKON_HOVER,
        "beckon:focus": BECKON_FOCUS,
        "beckon:sparkle": BECKON_SPARKLE,
        "job:started": JOB_STARTED,
        "job:assigned": JOB_ASSIGNED,
        "job:completed": JOB_COMPLETED,
        "job:failed": JOB_FAILED,
        "job:start": JOB_START,
        "job:assign": JOB_ASSIGN,
        "job:report-progress": JOB_REPORT_PROGRESS,
        "job:complete": JOB_COMPLETE,
        "job:fail": JOB_FAIL,
        "job:checkpoint": JOB_CHECKPOINT,
        "job:queued": JOB_QUEUED,
        "job:cancel-requested": JOB_CANCEL_REQUESTED,
        "job:cancel": JOB_CANCEL,
        "job:limits-requested": JOB_LIMITS_REQUESTED,
        "job:limits-result": JOB_LIMITS_RESULT,
        "job:limits-failed": JOB_LIMITS_FAILED,
        "job:status-requested": JOB_STATUS_REQUESTED,
        "job:create": JOB_CREATE,
        "job:claim": JOB_CLAIM,
        "job:status-result": JOB_STATUS_RESULT,
        "job:status-failed": JOB_STATUS_FAILED,
        "job:created": JOB_CREATED,
        "job:create-failed": JOB_CREATE_FAILED,
        "job:claimed": JOB_CLAIMED,
        "job:claim-failed": JOB_CLAIM_FAILED,
        "job:cancel-ok": JOB_CANCEL_OK,
        "job:cancel-failed": JOB_CANCEL_FAILED,
        "weave:applied": WEAVE_APPLIED,
        "smelt:settled": SMELT_SETTLED,
        "weave:rebuild": WEAVE_REBUILD,
        "weave:rebuild-ok": WEAVE_REBUILD_OK,
        "weave:rebuild-failed": WEAVE_REBUILD_FAILED,
        "smelt:rebuild-anchors": SMELT_REBUILD_ANCHORS,
        "smelt:rebuild-anchors-ok": SMELT_REBUILD_ANCHORS_OK,
        "smelt:rebuild-anchors-failed": SMELT_REBUILD_ANCHORS_FAILED,
        "settings:theme-changed": SETTINGS_THEME_CHANGED,
        "settings:line-numbers-toggled": SETTINGS_LINE_NUMBERS_TOGGLED,
        "settings:locale-changed": SETTINGS_LOCALE_CHANGED,
        "settings:hover-delay-changed": SETTINGS_HOVER_DELAY_CHANGED,
        "bus:resume-gap": BUS_RESUME_GAP,
        "session:joined": SESSION_JOINED,
        "session:left": SESSION_LEFT,
    }
)

# The channels a client hears with no scope held, unless it names a narrower list: every
# operation's result and failure, and the events sent to every client.
BRIDGED_CHANNELS: Final[tuple[ChannelName, ...]] = (
    "bind:body-updated",
    "bind:body-update-failed",
    "browse:resource-result",
    "browse:resource-failed",
    "browse:anchored-text-result",
    "browse:anchored-text-failed",
    "browse:resources-result",
    "browse:resources-failed",
    "browse:annotation-result",
    "browse:annotation-failed",
    "browse:annotations-result",
    "browse:annotations-failed",
    "browse:annotation-history-result",
    "browse:annotation-history-failed",
    "browse:events-result",
    "browse:events-failed",
    "browse:entity-types-result",
    "browse:entity-types-failed",
    "browse:tag-schemas-result",
    "browse:tag-schemas-failed",
    "browse:agents-result",
    "browse:agents-failed",
    "browse:kb-result",
    "browse:kb-failed",
    "browse:directory-result",
    "browse:directory-failed",
    "frame:entity-type-add-ok",
    "frame:entity-type-add-failed",
    "frame:tag-schema-add-ok",
    "frame:tag-schema-add-failed",
    "gather:complete",
    "gather:failed",
    "gather:resource-complete",
    "gather:resource-failed",
    "gather:summary-result",
    "gather:summary-failed",
    "gather:referenced-by-result",
    "gather:referenced-by-failed",
    "gather:limits-result",
    "gather:limits-failed",
    "job:created",
    "job:create-failed",
    "job:status-result",
    "job:status-failed",
    "job:limits-result",
    "job:limits-failed",
    "job:cancel-ok",
    "job:cancel-failed",
    "job:claimed",
    "job:claim-failed",
    "mark:create-ok",
    "mark:create-failed",
    "mark:commit-ok",
    "mark:commit-failed",
    "mark:delete-ok",
    "mark:delete-failed",
    "mark:archive-ok",
    "mark:archive-failed",
    "mark:unarchive-ok",
    "mark:unarchive-failed",
    "mark:update-entity-types-ok",
    "mark:update-entity-types-failed",
    "match:search-results",
    "match:search-failed",
    "match:resources-result",
    "match:resources-failed",
    "match:limits-result",
    "match:limits-failed",
    "weave:rebuild-ok",
    "weave:rebuild-failed",
    "smelt:rebuild-anchors-ok",
    "smelt:rebuild-anchors-failed",
    "yield:create-ok",
    "yield:create-failed",
    "yield:clone-persist-ok",
    "yield:clone-persist-failed",
    "yield:update-ok",
    "yield:update-failed",
    "yield:clone-created",
    "yield:clone-create-failed",
    "yield:clone-resource-result",
    "yield:clone-resource-failed",
    "yield:clone-token-generated",
    "yield:clone-token-failed",
    "job:report-progress",
    "job:complete",
    "job:fail",
    "smelt:settled",
    "frame:entity-type-added",
    "frame:tag-schema-added",
    "yield:created",
    "yield:updated",
    "yield:cloned",
    "yield:moved",
    "beckon:focus",
    "beckon:sparkle",
    "bus:resume-gap",
    "browse:resource-open",
    "browse:resource-viewed",
    "session:joined",
    "session:left",
    "browse:click",
)

# The channels a resource's scope carries: what holding a resource adds to a client's stream.
RESOURCE_SCOPED_CHANNELS: Final[tuple[ChannelName, ...]] = (
    "mark:body-updated",
    "yield:representation-added",
    "yield:representation-removed",
    "mark:added",
    "mark:removed",
    "mark:entity-tag-added",
    "mark:entity-tag-removed",
    "mark:archived",
    "mark:unarchived",
    "job:started",
    "job:assigned",
    "job:completed",
    "job:failed",
)
