/**
 * KnowledgeBase — a connection to a Semiont knowledge system.
 *
 * The KB type itself is uniform. The transport-shape variation lives in
 * the nested `endpoint` field, which is a discriminated union:
 *
 *  - `endpoint.kind === 'http'`  — a remote backend reached over HTTP+SSE.
 *                                  Carries `host`/`port`/`protocol`.
 *  - `endpoint.kind === 'local'` — an in-process knowledge system reached
 *                                  via `LocalTransport` from
 *                                  `@semiont/make-meaning`. Carries an
 *                                  opaque `kbId` identifying the local
 *                                  instance to the host process.
 *
 * Code that doesn't know how to make a transport (`SemiontSession`,
 * `SemiontBrowser`, the frontend KB list UI) treats `KnowledgeBase` as
 * uniform and never inspects `endpoint`. Code that *does* construct
 * transports (the transport-factory passed to `SemiontBrowser`,
 * `kbBackendUrl` for HTTP URL construction) inspects `endpoint.kind`
 * and dispatches.
 *
 * Each KB has its own session, its own credentials (where applicable),
 * and its own JWT (HTTP only). The user is "authenticated against KB X" —
 * never globally authenticated.
 */

/** Fields shared by every KB regardless of endpoint kind. */
export interface KnowledgeBase {
  id: string;
  label: string;
  email: string;
  gitBranch?: string;
  endpoint: KbEndpoint;
}

export type KbEndpoint = HttpEndpoint | LocalEndpoint;

export interface HttpEndpoint {
  kind: 'http';
  host: string;
  port: number;
  protocol: 'http' | 'https';
}

export interface LocalEndpoint {
  kind: 'local';
  /** Opaque identifier for the in-process KB instance the host has loaded. */
  kbId: string;
}

/**
 * Input shape for adding a new KB. The id is generated by the provider.
 */
export type NewKnowledgeBase = Omit<KnowledgeBase, 'id'>;

/**
 * Status of the locally-stored credential for a KB. Derived from the
 * presence and validity of the JWT in session storage.
 */
export type KbSessionStatus = 'authenticated' | 'expired' | 'signed-out' | 'unreachable';

/**
 * Construct a `KnowledgeBase` for an HTTP-backed Semiont backend without
 * spelling out the nested `endpoint` literal. Convenience for tests,
 * worker bootstraps, and one-off scripts.
 *
 * ```ts
 * const kb = httpKb({
 *   id: 'my-watcher',
 *   label: 'My Watcher',
 *   email: 'me@example.com',
 *   host: 'localhost',
 *   port: 4000,
 *   protocol: 'http',
 * });
 * ```
 *
 * Equivalent to:
 *
 * ```ts
 * const kb: KnowledgeBase = {
 *   id, label, email,
 *   endpoint: { kind: 'http', host, port, protocol },
 * };
 * ```
 *
 * UI hosts that have a structured form (host / port / protocol pickers)
 * already construct the literal directly — they don't need this helper.
 * Local-endpoint KBs construct the literal directly too; the local
 * endpoint shape (`{ kind: 'local', kbId }`) is one line and doesn't
 * earn a helper.
 */
export function httpKb(opts: {
  id: string;
  label: string;
  email: string;
  host: string;
  port: number;
  protocol: 'http' | 'https';
  gitBranch?: string;
}): KnowledgeBase {
  const { id, label, email, host, port, protocol, gitBranch } = opts;
  return {
    id,
    label,
    email,
    ...(gitBranch !== undefined ? { gitBranch } : {}),
    endpoint: { kind: 'http', host, port, protocol },
  };
}
