/**
 * KnowledgeBase — a connection to a Semiont knowledge system.
 *
 * The KB type itself is uniform. The transport-shape variation lives in
 * the nested `endpoint` field, which is a discriminated union:
 *
 *  - `endpoint.kind === 'http'`  — a remote gateway reached over HTTP+SSE.
 *                                  Carries `host`/`port`/`protocol`.
 *  - `endpoint.kind === 'local'` — an in-process knowledge system reached
 *                                  via `LocalTransport` from
 *                                  `@semiont/make-meaning`. Carries an
 *                                  opaque `kbId` identifying the local
 *                                  instance to the host process.
 *
 * Code that doesn't know how to make a transport (`SemiontSession`,
 * `SemiontBrowser`, the frontend KB list UI) treats `KnowledgeBase` as
 * uniform and never inspects `endpoint`. Code that *does* construct
 * transports (the transport-factory passed to `SemiontBrowser`,
 * `kbGatewayUrl` for HTTP URL construction) inspects `endpoint.kind`
 * and dispatches.
 *
 * Each KB has its own session, its own credentials (where applicable),
 * and its own JWT (HTTP only). The user is "authenticated against KB X" —
 * never globally authenticated.
 */

import type { KbDescription } from '@semiont/core';

/**
 * **Where to connect** — an address plus the labels a host keeps locally.
 * Deliberately carries NO identity: you cannot know which knowledge base
 * answers at an address until you have authenticated and asked it
 * (`browse.kb()` needs a token), so a target is what every caller can
 * honestly construct up front — a session's whole input, and what `httpKb`
 * returns.
 *
 * This split is .plans/KB-IDENTITY-VS-ADDRESS.md's thesis in the type
 * system: an address is not an identity. Collapsing the two forced the
 * question "what do I put here?" on callers who cannot answer it, and the
 * only available answers were fabrications.
 */
export interface KbTarget {
  id: string;
  label: string;
  endpoint: KbEndpoint;
}

/**
 * A **registered** knowledge base: a target plus the identity the KB itself
 * reported (`browse.kb()`). This is the shape the KB list stores and the
 * discovery join compares against — everything past the point where identity
 * is knowable.
 *
 * `did` is REQUIRED here, and only here: a knowledge base declares its
 * identity or does not run (decision 8 — the launcher refuses to start one
 * without a `[site] domain`, and the gateway refuses to boot), so anything
 * that has been connected to *has* a did. What was previously unknowable is
 * now simply a `KbTarget`.
 *
 * It says **which knowledge base**, not **which running copy**, and it is
 * deliberately NOT unique: a local clone and a codespace of one repo are the
 * same KB at two addresses and report the same did (decision 9). When
 * matching a registered KB against discovered entries, look up by `endpoint`
 * — the unique field — and use this to *verify* the copy you reached is the
 * KB you meant. Never select on it.
 */
export interface KnowledgeBase extends KbTarget {
  did: string;
  /**
   * The last time this KB described itself, and what it said beyond its name
   * (which is `label`). Written only from a read whose did matched this
   * entry's; absent until one has.
   */
  lastRead?: KbRead;
}

/**
 * When a KB last described itself, and the live part of what it said. A host
 * shows it as current only while a session to the KB is live, and as of `at`
 * otherwise.
 */
export interface KbRead {
  /** When the answer arrived, ISO 8601. */
  at: string;
  /** The working tree's branch then; absent when it was not a git checkout. */
  gitBranch?: string;
}

export function kbRead(description: KbDescription, at: Date): KbRead {
  return {
    at: at.toISOString(),
    ...(description.gitBranch !== undefined ? { gitBranch: description.gitBranch } : {}),
  };
}

export type KbEndpoint = HttpEndpoint | LocalEndpoint;

export interface HttpEndpoint {
  kind: 'http';
  host: string;
  port: number;
  protocol: 'http' | 'https';
}

export interface LocalEndpoint {
  kind: 'local';
  /** Opaque identifier for the in-process KB instance the host has loaded. */
  kbId: string;
}

/**
 * Input shape for REGISTERING a KB (the id is generated by the provider).
 * Includes `did`, because registration happens after authentication — the
 * caller has already been told, by the KB itself, what it is.
 */
export type NewKnowledgeBase = Omit<KnowledgeBase, 'id'>;

/**
 * Status of the locally-stored credential for a KB. Derived from the
 * presence and validity of the JWT in session storage.
 */
export type KbSessionStatus = 'authenticated' | 'expired' | 'signed-out' | 'unreachable';

/**
 * Construct a `KnowledgeBase` for an HTTP-backed Semiont gateway without
 * spelling out the nested `endpoint` literal. Convenience for tests,
 * worker bootstraps, and one-off scripts.
 *
 * ```ts
 * const kb = httpKb({
 *   id: 'my-watcher',
 *   label: 'My Watcher',
 *   host: 'localhost',
 *   port: 4000,
 *   protocol: 'http',
 * });
 * ```
 *
 * Equivalent to:
 *
 * ```ts
 * const kb: KbTarget = {
 *   id, label,
 *   endpoint: { kind: 'http', host, port, protocol },
 * };
 * ```
 *
 * UI hosts that have a structured form (host / port / protocol pickers)
 * already construct the literal directly — they don't need this helper.
 * Local-endpoint KBs construct the literal directly too; the local
 * endpoint shape (`{ kind: 'local', kbId }`) is one line and doesn't
 * earn a helper.
 */
export function httpKb(opts: {
  id: string;
  label: string;
  host: string;
  port: number;
  protocol: 'http' | 'https';
}): KbTarget {
  const { id, label, host, port, protocol } = opts;
  return {
    id,
    label,
    endpoint: { kind: 'http', host, port, protocol },
  };
}
