/**
 * Integration tests for authentication
 * Bearer-only: the token rides the Authorization header, never a cookie, and logout revokes it.
 */

import { describe, it, expect, beforeAll, beforeEach, vi } from 'vitest';

import { makeMeaningMock } from '../helpers/make-meaning-mock';

// Mock make-meaning service to avoid graph initialization at import time
vi.mock('@semiont/make-meaning', async (importOriginal) => {
  const actual = await importOriginal() as any;
  return {
    ...actual,
    startMakeMeaningGateway: vi.fn().mockResolvedValue(makeMeaningMock())
  };
});

import { app } from '../../index';
import { DatabaseConnection } from '../../db';
import { JWTService } from '../../auth/jwt';
import { User } from '@prisma/client';
import { faker } from '@faker-js/faker';


const prisma = DatabaseConnection.getClient();
const mockPrismaUser = vi.mocked(prisma.user);

describe('Authentication Integration', () => {
  beforeAll(() => {
    // Initialize JWTService with test config
    JWTService.initialize({
      site: { domain: 'test.local' },
    });
  });

  beforeEach(() => {
    vi.clearAllMocks();
  });

  // JWTPayloadSchema requires CUID format: /^c[a-z0-9]{24,}$/
  const makeCuid = () => `c${faker.string.alphanumeric(24).toLowerCase()}`;

  describe('Bearer-only auth (no cookie fallback)', () => {
    // These tests use a real JWT generated by JWTService and mock only the Prisma lookup,
    // which is the same path principalFromToken takes internally.
    const makeTokenAndUser = () => {
      const { email: makeEmail } = require('@semiont/core');
      const user: User = {
        id: makeCuid(),
        email: 'cookieauth@example.com',
        name: 'Cookie Auth User',
        image: null,
        domain: 'example.com',
        provider: 'google',
        providerId: 'google-ca-123',
        isAdmin: false,
        isModerator: false,
        lastLogin: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      };
      const token = JWTService.generateToken({        did: `did:web:${user.domain}:agents:test:model`,

        email: makeEmail(user.email),
        domain: user.domain,
      });
      return { user, token };
    };

    it('rejects a request carrying only the semiont-token cookie (no Authorization header) → 401', async () => {
      const { user, token } = makeTokenAndUser();
      mockPrismaUser.findUnique.mockResolvedValue(user);

      const response = await app.request('/api/users/me', {
        headers: { 'Cookie': `semiont-token=${token}` },
      });

      expect(response.status).toBe(401);
    });

    it('should return 401 when no Authorization header and no cookie are present', async () => {
      const response = await app.request('/api/users/me');

      expect(response.status).toBe(401);
      const data = await response.json() as { error: string };
      expect(data.error).toBe('Unauthorized');
    });

    it('ignores a stray cookie; a bearer token still authenticates', async () => {
      const { email: makeEmail } = require('@semiont/core');
      const bearerUser: User = {
        id: makeCuid(),
        email: 'bearer@example.com',
        name: 'Bearer User',
        image: null,
        domain: 'example.com',
        provider: 'google',
        providerId: 'google-bearer-123',
        isAdmin: false,
        isModerator: false,
        lastLogin: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      };
      const bearerToken = JWTService.generateToken({        did: `did:web:${bearerUser.domain}:agents:test:model`,

        email: makeEmail(bearerUser.email),
        domain: bearerUser.domain,
      });
      // Only the bearer user lookup should happen (Authorization header wins)
      mockPrismaUser.findUnique.mockResolvedValue(bearerUser);

      const response = await app.request('/api/users/me', {
        headers: {
          'Authorization': `Bearer ${bearerToken}`,
          'Cookie': 'semiont-token=some-other-invalid-token',
        },
      });

      expect(response.status).toBe(200);
      const data = await response.json() as { did: string; email: string };
      expect(data.email).toBe(bearerUser.email);
      // A gateway-signed token names its own DID; the endpoint echoes what the
      // token said rather than re-deriving it from a row it no longer reads.
      expect(data.did).toBe(`did:web:${bearerUser.domain}:agents:test:model`);
    });
  });


});
