/**
 * Integration tests for authentication
 * Bearer-only: the token rides the Authorization header, never a cookie, and logout revokes it.
 */

import { describe, it, expect, beforeAll, beforeEach, vi } from 'vitest';

import { makeMeaningMock } from '../helpers/make-meaning-mock';

// Mock make-meaning service to avoid graph initialization at import time
vi.mock('@semiont/make-meaning', async (importOriginal) => {
  const actual = await importOriginal() as any;
  return {
    ...actual,
    startMakeMeaningGateway: vi.fn().mockResolvedValue(makeMeaningMock())
  };
});

import { app } from '../../index';
import { JWTService } from '../../auth/jwt';
import type { Principal } from '../../identity/principal';



describe('Authentication Integration', () => {
  beforeAll(() => {
    // Initialize JWTService with test config
    JWTService.initialize({
      site: { domain: 'test.local' },
    });
  });

  beforeEach(() => {
    vi.clearAllMocks();
  });

  // JWTPayloadSchema requires CUID format: /^c[a-z0-9]{24,}$/

  describe('Bearer-only auth (no cookie fallback)', () => {
    // These tests use a real JWT generated by JWTService and take the same path
    // principalFromToken does internally. Nothing is looked up: the principal is
    // built from the token's own claims.
    const makeTokenAndUser = () => {
      const { email: makeEmail } = require('@semiont/core');
      const user: Principal = {
        did: `did:web:${'example.com'}:users:${encodeURIComponent('cookieauth@example.com')}`,
        email: 'cookieauth@example.com',
        name: 'Cookie Auth User',
        image: null,
        domain: 'example.com',
        isAgent: false,
      };
      const token = JWTService.generateToken({        did: `did:web:${user.domain}:agents:test:model`,

        email: makeEmail(user.email),
        domain: user.domain,
      }, '1h');
      return { user, token };
    };

    it('rejects a request carrying only the semiont-token cookie (no Authorization header) → 401', async () => {
      const { token } = makeTokenAndUser();

      const response = await app.request('/api/users/me', {
        headers: { 'Cookie': `semiont-token=${token}` },
      });

      expect(response.status).toBe(401);
    });

    it('should return 401 when no Authorization header and no cookie are present', async () => {
      const response = await app.request('/api/users/me');

      expect(response.status).toBe(401);
      const data = await response.json() as { error: string };
      expect(data.error).toBe('Unauthorized');
    });

    it('ignores a stray cookie; a bearer token still authenticates', async () => {
      const { email: makeEmail } = require('@semiont/core');
      const bearerUser: Principal = {
        did: `did:web:${'example.com'}:users:${encodeURIComponent('bearer@example.com')}`,
        email: 'bearer@example.com',
        name: 'Bearer User',
        image: null,
        domain: 'example.com',
        isAgent: false,
      };
      const bearerToken = JWTService.generateToken({        did: `did:web:${bearerUser.domain}:agents:test:model`,

        email: makeEmail(bearerUser.email),
        domain: bearerUser.domain,
      }, '1h');
      // Only the bearer user lookup should happen (Authorization header wins)

      const response = await app.request('/api/users/me', {
        headers: {
          'Authorization': `Bearer ${bearerToken}`,
          'Cookie': 'semiont-token=some-other-invalid-token',
        },
      });

      expect(response.status).toBe(200);
      const data = await response.json() as { did: string; email: string };
      expect(data.email).toBe(bearerUser.email);
      // A gateway-signed token names its own DID; the endpoint echoes what the
      // token said rather than re-deriving it from a row it no longer reads.
      expect(data.did).toBe(`did:web:${bearerUser.domain}:agents:test:model`);
    });
  });


});
