#!/usr/bin/env node

import { build } from 'esbuild'
import { readdir, mkdir, writeFile, readFile, cp } from 'fs/promises'
import { existsSync } from 'fs'
import { join } from 'path'

// Read version from package.json
const packageJson = JSON.parse(await readFile('package.json', 'utf-8'))
const version = packageJson.version || '0.0.1'

// Ensure dist directory exists
if (!existsSync('dist')) {
  await mkdir('dist', { recursive: true })
}

// Build dashboard bundle first
console.log('🎨 Building web dashboard...')
const dashboardDir = join('dist', 'dashboard')
if (!existsSync(dashboardDir)) {
  await mkdir(dashboardDir, { recursive: true })
}

try {
  // Build the React dashboard bundle
  await build({
    entryPoints: ['src/core/dashboard/web-dashboard-app.tsx'],
    bundle: true,
    minify: true,
    sourcemap: true,
    format: 'iife',
    globalName: 'SemiontDashboard',
    outfile: join(dashboardDir, 'dashboard.js'),
    platform: 'browser',
    target: ['chrome90', 'firefox88', 'safari14', 'edge90'],
    define: {
      'process.env.NODE_ENV': '"production"',
      'global': 'window'
    },
    banner: {
      js: `
// Map external modules to globals
const React = window.React;
const ReactDOM = window.ReactDOM;
const require = (name) => {
  if (name === 'react') return React;
  if (name === 'react-dom') return ReactDOM;
  throw new Error('Unknown module: ' + name);
};
`
    },
    footer: {
      js: '// Ensure global is set\nif (typeof window !== "undefined") { window.SemiontDashboard = SemiontDashboard; }'
    },
    external: [
      // These are loaded via CDN in the HTML
      'react',
      'react-dom'
    ],
    loader: {
      '.tsx': 'tsx',
      '.ts': 'ts',
      '.css': 'css'
    }
  })

  // Append dashboard layout CSS to the react-ui bundle output by esbuild
  const layoutCss = await readFile('src/core/dashboard/dashboard.css', 'utf-8')

  const cssOutPath = join(dashboardDir, 'dashboard.css')
  const { appendFileSync, writeFileSync, existsSync: fsExistsSync } = await import('fs')
  if (fsExistsSync(cssOutPath)) {
    appendFileSync(cssOutPath, layoutCss)
  } else {
    writeFileSync(cssOutPath, layoutCss)
  }
  console.log('✅ Dashboard bundle built successfully')

  // Now embed the dashboard assets into TypeScript file
  const dashboardJS = await readFile(join(dashboardDir, 'dashboard.js'), 'utf-8')
  const dashboardCSS = await readFile(join(dashboardDir, 'dashboard.css'), 'utf-8')
  
  const embeddedContent = `/**
 * Auto-generated file containing embedded dashboard assets
 * DO NOT EDIT MANUALLY - Generated by build.mjs
 */

export const embeddedDashboardJS = ${JSON.stringify(dashboardJS)};

export const embeddedDashboardCSS = ${JSON.stringify(dashboardCSS)};

export const dashboardAssetsEmbedded = true;
`
  
  await writeFile('src/core/dashboard/embedded-assets.ts', embeddedContent)
  console.log('✅ Dashboard assets embedded')
  
} catch (error) {
  console.error('❌ Failed to build dashboard:', error.message)
  process.exit(1)
}

// Get all TypeScript files in the src directory (excluding config files)
const scriptFiles = (await readdir('src', { withFileTypes: true }))
  .filter(dirent => dirent.isFile() && (dirent.name.endsWith('.ts') || dirent.name.endsWith('.tsx')) && dirent.name !== 'build.ts' && !dirent.name.includes('.config.'))
  .map(dirent => dirent.name.replace(/\.tsx?$/, ''))

const totalFiles = scriptFiles.length
console.log(`📦 Bundling ${totalFiles} files with esbuild...`)

// Build root files
await Promise.all(scriptFiles.map(async (name) => {
  // Check if .tsx exists first, then .ts
  const tsxExists = existsSync(`src/${name}.tsx`);
  const entryPoint = tsxExists ? `src/${name}.tsx` : `src/${name}.ts`;
  const outFile = `dist/${name}.mjs`
  
  try {
    await build({
      entryPoints: [entryPoint],
      bundle: true,
      platform: 'node',
      target: 'node20',
      format: 'esm',
      outfile: outFile,
      jsx: 'automatic',
      jsxImportSource: 'react',
      external: [
        // Node.js built-ins that can't be bundled
        'fs',
        'path',
        'child_process',
        'crypto',
        'os',
        'util',
        'stream',
        'events',
        'buffer',
        'url',
        'querystring',
        'module',
        // Don't bundle these Node.js built-ins and external binaries
        'aws-cli',
        'docker',
        'podman',
        // React and Ink - keep external to avoid ESM/top-level await issues
        'react',
        'ink',
        'react-devtools-core',
        // AWS SDK packages have complex CommonJS/ESM interactions
        '@aws-sdk/*',
        // CDK is optional - projects can provide their own
        'aws-cdk-lib',
        'constructs',
        // Local workspace packages - keep external to avoid CommonJS/ESM issues
        '@semiont/api-types',
        '@semiont/api-client',
        '@semiont/core',
        '@semiont/content',
        '@semiont/event-sourcing',
        '@semiont/graph',
        '@semiont/make-meaning',
        // Native binaries that can't be bundled
        'ssh2',
        'cpu-features',
        'argon2',
        // Large dependencies that work better as external
        '@testcontainers/postgresql',
        // Express and Socket.IO need to be external due to CommonJS/ESM issues
        'express',
        'socket.io',
        // simple-git uses dynamic requires that don't work with bundling
        'simple-git',
        // neo4j-driver uses dynamic requires for node internals
        'neo4j-driver',
        'neo4j-driver-core',
        // esbuild is needed at runtime for compiling CDK stacks
        'esbuild',
        // Vitest and testing dependencies
        'vitest',
        '@vitest/browser',
        'lightningcss',
        'fsevents',
        'vite'
      ],
      define: {
        // Disable ink devtools in production bundles
        'process.env.NODE_ENV': '"production"',
        // Inline Semiont version at build time
        '__SEMIONT_VERSION__': JSON.stringify(version)
      },
      banner: {
        js: '#!/usr/bin/env node\n'
      },
      logLevel: 'warning'
    })
    console.log(`✅ ${name}`)
  } catch (error) {
    console.error(`❌ ${name}:`, error.message)
    process.exit(1)
  }
}))

console.log(`🎉 All files bundled successfully!`)

// Copy templates directory to dist
if (existsSync('templates')) {
  try {
    await cp('templates', 'dist/templates', { recursive: true })
    console.log('✅ Copied templates directory')
  } catch (error) {
    console.error('❌ Failed to copy templates:', error.message)
    process.exit(1)
  }
}

// Copy dashboard bundle to dist
if (existsSync('dist/dashboard')) {
  try {
    // Dashboard is already in dist, but we need to ensure it's preserved
    console.log('✅ Dashboard bundle found in dist/dashboard')
  } catch (error) {
    console.error('❌ Failed to verify dashboard:', error.message)
  }
} else {
  console.log('⚠️  Dashboard bundle not found. Run "npm run build:dashboard" to build it.')
}

// Copy staged @semiont/frontend into dist/frontend/ so it travels with the CLI tarball.
const frontendStageSrc = '../../.npm-stage/frontend'
if (existsSync(frontendStageSrc)) {
  try {
    const frontendDest = 'dist/frontend'
    if (existsSync(frontendDest)) {
      const { rmSync } = await import('fs')
      rmSync(frontendDest, { recursive: true })
    }
    await cp(frontendStageSrc, frontendDest, { recursive: true })
    console.log('✅ Copied @semiont/frontend into dist/frontend')
  } catch (error) {
    console.error('❌ Failed to copy @semiont/frontend:', error.message)
    process.exit(1)
  }
} else {
  console.warn('⚠️  .npm-stage/frontend not found — run `node scripts/ci/publish-npm-apps.mjs` first to stage the frontend')
}

// Copy MCP server to dist
const mcpServerSrc = '../../packages/mcp-server/dist'
if (existsSync(mcpServerSrc)) {
  try {
    await cp(mcpServerSrc, 'dist/mcp-server', { recursive: true })
    console.log('✅ Copied MCP server')
  } catch (error) {
    console.error('❌ Failed to copy MCP server:', error.message)
    process.exit(1)
  }
}

// Ensure CLI entry point has execute permissions
import { chmod } from 'node:fs/promises'
try {
  await chmod('dist/cli.mjs', 0o755)
  console.log('✅ Set execute permissions on CLI entry point')
} catch (error) {
  console.error('❌ Failed to set execute permissions:', error.message)
  process.exit(1)
}

