/**
 * @semiont/core
 *
 * Core domain logic and utilities for the Semiont semantic knowledge platform.
 * OpenAPI types are generated here and exported for use across the monorepo.
 */
export type { components, paths, operations } from './types';
export type { Motivation, ContentFormat, Email, AuthCode, GoogleCredential, AccessToken, RefreshToken, MCPToken, CloneToken, JobId, UserDID, EntityType, SearchQuery, BaseUrl, ResourceUri, AnnotationUri, ResourceAnnotationUri, } from './branded-types';
export { email, authCode, googleCredential, accessToken, refreshToken, mcpToken, cloneToken, jobId, userDID, entityType, searchQuery, baseUrl, resourceUri, annotationUri, resourceAnnotationUri, } from './branded-types';
export type { ResourceId, AnnotationId, UserId } from './identifiers';
export { resourceId, annotationId, userId, isResourceId, isAnnotationId, } from './identifiers';
export type { GraphConnection, GraphPath, EntityTypeStats, ResourceDescriptor, } from './graph';
export type { Brand, EventBase, EventMetadata, EventSignature, StoredEvent, BodyOperation, BodyItem, EventQuery, ResourceAnnotations, } from './event-base';
export type { EventOfType, PersistedEvent, PersistedEventType, EventInput, } from './persisted-events';
export { PERSISTED_EVENT_TYPES } from './persisted-events';
export type { EventMap, EventName, EmittableChannel, ResourceBroadcastType, AnchorRect, } from './bus-protocol';
export { RESOURCE_BROADCAST_TYPES, CHANNEL_SCHEMAS } from './bus-protocol';
export type { Selector, GatheredContext, GenerationJobParams, SelectionData, JobType, CollaboratorEntry, DiscoveryDocument, DiscoveredKB, } from './payload-types';
export type { StoredEventLike } from './event-utils';
export { getAnnotationUriFromEvent, isEventRelatedToAnnotation, isStoredEvent, } from './event-utils';
export { EventBus, ScopedEventBus } from './event-bus';
export { burstBuffer, type BurstBufferOptions } from './operators/burst-buffer';
export { serializePerKey } from './serialize-per-key';
export type { Logger } from './logger';
export { errField } from './logger';
export { busLog, busLogEnabled, setBusLogTraceIdProvider, type BusOp } from './bus-log';
export { findBodyItem } from './annotation-utils';
export type { BodyItemIdentity } from './annotation-utils';
export { assembleAnnotation, applyBodyOperations, getTextPositionSelector, getSvgSelector, getFragmentSelector, validateSvgMarkup, } from './annotation-assembly';
export type { AssembledAnnotation } from './annotation-assembly';
export { getBodySource, getBodyType, isBodyResolved, getTargetSource, getTargetSelector, hasTargetSelector, isHighlight, isReference, isAssessment, isComment, isTag, getCommentText, isStubReference, isResolvedReference, getExactText, getAnnotationExactText, getPrimarySelector, getTextQuoteSelector, extractBoundingBox, } from './web-annotation-utils';
export type { TextPositionSelector, TextQuoteSelector, SvgSelector, FragmentSelector, } from './web-annotation-utils';
export { createFragmentSelector, parseFragmentSelector, getPageFromFragment, } from './pdf-coordinates';
export type { PdfCoordinate } from './pdf-coordinates';
export { locate, textUnder, anchorRuns, isTextRun } from './pdf-anchoring';
export { findClaimSpan } from './pdf-citation-search';
export type { AnchoredText, AnchoredTextAnswer, ExtractionOutcome, PdfTextItem, PdfTextRun } from './pdf-anchoring';
export { getResourceId, getPrimaryRepresentation, getPrimaryMediaType, getChecksum, getLanguage, getStorageUri, getCreator, getDerivedFrom, isArchived, getResourceEntityTypes, isDraft, getNodeEncoding, decodeRepresentation, } from './resource-utils';
export type { ITransport, IGatewayOperations, IContentTransport, PutBinaryRequest, PutBinaryOptions, PutBinaryProgress, ConnectionState, HealthCheckResponse, StatusResponse, UserResponse, UpdateUserRequest, UpdateUserResponse, ListUsersResponse, } from './transport';
export { BRIDGED_CHANNELS, type BridgedChannel } from './bridged-channels';
export { busRequest, replyChannelsFor, BusRequestError, type BusRequestErrorCode, type BusRequestPrimitive } from './bus-request';
export { BUS_OPERATIONS, type BusOperationKey, type BusOperationSpec } from './bus-operations';
export { normalizeText, buildContentCache, findBestTextMatch, verifyPosition, } from './fuzzy-anchor';
export type { TextPosition, MatchQuality, ContentCache } from './fuzzy-anchor';
export { anchorAnnotation, POSITION_WINDOW, CONTEXT_FULL_WEIGHT, CONTEXT_PARTIAL_WEIGHT, POSITION_WEIGHT_MAX, } from './anchor-annotation';
export type { AnchorStrategy, AnchorConfidence, RenderedAnchor, AnchorSelectors, } from './anchor-annotation';
export { LOCALES, getLocaleInfo, getLocaleNativeName, getLocaleEnglishName, formatLocaleDisplay, getAllLocaleCodes, } from './locales';
export type { LocaleInfo } from './locales';
export { createRectangleSvg, createPolygonSvg, createCircleSvg, parseSvgSelector, normalizeCoordinates, scaleSvgToNative, } from './svg-utils';
export type { Point, BoundingBox } from './svg-utils';
export { extractContext, reconcileSelector } from './text-context';
export type { ReconciledSelector, AnchorMethod, LlmSelectorInput } from './text-context';
export { extractCharset, decodeWithCharset } from './text-encoding';
export { JWTTokenSchema, validateData, isValidEmail, } from './validation';
export type { ValidationSuccess, ValidationFailure, ValidationResult } from './validation';
export { MEDIA_TYPES, baseMediaType, isSupportedMediaType, capabilitiesOf, cloneFormat, extensionForMediaType, mediaTypeForExtension, textSourceOf, yieldsGeometryOf, isAnnotatable, AUTHORABLE_MEDIA_TYPES, EMBEDDABLE_MEDIA_TYPES, GENERATABLE_MEDIA_TYPES, } from './media-types';
export type { SupportedMediaType, MediaTypeCapabilities, RenderMode, AnchoringModel, TextSource, } from './media-types';
export type { UpdateResourceInput, ResourceFilter, StoredResource } from './resource-types';
export type { Annotation, AnnotationCategory, CreateAnnotationInternal } from './annotation-types';
export type { TagSchema, TagCategory } from './tag-schemas';
export type { GoogleAuthRequest } from './auth-types';
export { generateUuid, uuidV4 } from './id-generation';
export { chunkText, estimateTokens, DEFAULT_CHUNKING_CONFIG } from './chunking';
export type { ChunkingConfig } from './chunking';
export type { StateUnit } from './state-unit';
export * from './storage-uri';
export * from './type-guards';
export * from './errors';
export * from './did-utils';
export type { EnvironmentConfig, SiteConfig, AppConfig, } from './config/config.types';
export { loadTomlConfig, createTomlConfigLoader, type TomlFileReader, type InferenceConfig as TomlInferenceConfig, type ActorInferenceConfig as TomlActorInferenceConfig, type WorkerInferenceConfig as TomlWorkerInferenceConfig, } from './config/toml-loader';
export { parseEnvironment, validateEnvironment, type Environment, } from './config/environment-validator';
export { ConfigurationError } from './config/configuration-error';
export { type PlatformType, isValidPlatformType, getAllPlatformTypes, } from './config/platform-types';
export type { GatewayServiceConfig, DatabaseServiceConfig, GraphServiceConfig, OllamaProviderConfig, AnthropicProviderConfig, InferenceProvidersConfig, McpServiceConfig, ArchivistServiceConfig, ServicesConfig, VectorsServiceConfig, EmbeddingServiceConfig, SemiontConfig, GraphDatabaseType, ServicePlatformConfig } from './config/config.types';
export { deriveViews } from './knowledge-graph-views';
export type { GraphViews } from './knowledge-graph-views';
export { retryWithBackoff, isTransientFetchError, STARTUP_FETCH_RETRY } from './retry';
export type { RetryPolicy, RetryAttemptInfo } from './retry';
export { getShardPath, jumpConsistentHash } from './shard-utils';
export { DISCOVERY_URL_PATH } from './discovery';
